# Generated by Django 5.0.7 on 2025-10-03 12:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="header_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="blog_headers"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
