# Generated by Django 5.0.7 on 2025-08-31 09:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BentoGridItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subtitle", models.CharField(max_length=255)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="bento_grid_images"
                    ),
                ),
                ("link_url", models.URLField(blank=True, max_length=500)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "column_span",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many columns this item should span (e.g., 1, 2).",
                    ),
                ),
                (
                    "row_span",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many rows this item should span (e.g., 1, 2).",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Brochure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Our Free Brochure", max_length=200),
                ),
                (
                    "pdf_file",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Upload the brochure PDF file here.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Brochure",
            },
        ),
        migrations.CreateModel(
            name="ChatbotQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        help_text="The short keyword/bubble text.", max_length=100
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        help_text="The full question for autocompletion.",
                        max_length=255,
                    ),
                ),
                ("answer", models.TextField()),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Chatbot Q&A",
                "ordering": ["display_order"],
            },
        ),
    ]
