# Generated by Django 5.0.7 on 2025-10-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_bentogriditem_brochure_chatbotqa"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategycalllead",
            name="interest",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="strategycalllead",
            name="message",
            field=models.TextField(default=""),
        ),
    ]
