# Generated by Django 5.0.7 on 2025-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0003_strategycalllead_interest_strategycalllead_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategycalllead",
            name="biggest_challenge",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="strategycalllead",
            name="interest",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="strategycalllead",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="strategycalllead",
            name="success_goal",
            field=models.TextField(blank=True),
        ),
    ]
