# Generated by Django 5.0.7 on 2025-08-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Check this to feature the post in the Blog page carousel.",
            ),
        ),
    ]
