# Generated by Django 5.0.7 on 2025-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_header_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Check this to feature the post in the homepage carousel.",
            ),
        ),
    ]
