# Generated by Django 5.0.7 on 2025-10-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_header_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Check this to feature the post in the Blog page carousel.",
            ),
        ),
    ]
