# Generated by Django 5.0.7 on 2025-08-31 06:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfficeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Headquarters, Design Studio", max_length=100
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("google_maps_link", models.URLField(max_length=500)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="logo"
                    ),
                ),
                (
                    "hero_image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="hero_image"
                    ),
                ),
                ("hero_image_opacity", models.PositiveIntegerField(default=20)),
                ("hero_image_blur", models.PositiveIntegerField(default=5)),
                ("enable_dark_mode", models.BooleanField(default=True)),
                (
                    "footer_background_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="footer_background",
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="thedearandco@gmail.com", max_length=254),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="9846547132",
                        help_text="Enter phone number without country code or symbols.",
                        max_length=20,
                    ),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        blank=True,
                        help_text="e.g., https://wa.me/919846547132",
                        max_length=255,
                    ),
                ),
                ("instagram", models.URLField(blank=True, max_length=255)),
                ("facebook", models.URLField(blank=True, max_length=255)),
                ("linkedin", models.URLField(blank=True, max_length=255)),
                ("behance", models.URLField(blank=True, max_length=255)),
                ("discord", models.URLField(blank=True, max_length=255)),
                ("youtube", models.URLField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
