# Generated by Django 5.0.7 on 2025-08-30 11:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="project_images"
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="team_images"
            ),
        ),
    ]
