# Generated by Django 5.0.7 on 2025-08-30 14:50

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Your site's primary logo. Should be a transparent PNG.",
                        max_length=255,
                        null=True,
                        verbose_name="logo",
                    ),
                ),
                (
                    "hero_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="The main background image for the homepage hero section.",
                        max_length=255,
                        null=True,
                        verbose_name="hero_image",
                    ),
                ),
                (
                    "hero_image_opacity",
                    models.PositiveIntegerField(
                        default=20, help_text="Opacity of the hero image (0-100)."
                    ),
                ),
                (
                    "hero_image_blur",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Blur effect on the hero image in pixels (0-20).",
                    ),
                ),
                (
                    "enable_dark_mode",
                    models.BooleanField(
                        default=True,
                        help_text="Enable the dark mode theme for the entire site.",
                    ),
                ),
                (
                    "footer_background_image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Background image for the footer section.",
                        max_length=255,
                        null=True,
                        verbose_name="footer_background",
                    ),
                ),
                (
                    "company_address",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 123 Creative Lane, Digital City, 45678",
                        max_length=255,
                    ),
                ),
                (
                    "google_maps_link",
                    models.URLField(
                        blank=True,
                        default="https://share.google/WxcaWdKqqUTiSjRMA",
                        max_length=500,
                    ),
                ),
                (
                    "email",
                    models.EmailField(default="thedearandco@gmail.com", max_length=254),
                ),
                (
                    "whatsapp",
                    models.URLField(
                        blank=True,
                        help_text="e.g., https://wa.me/919846547132",
                        max_length=255,
                    ),
                ),
                (
                    "instagram",
                    models.URLField(
                        blank=True,
                        help_text="e.g., https://www.instagram.com/thedearandco/",
                        max_length=255,
                    ),
                ),
                ("facebook", models.URLField(blank=True, max_length=255)),
                ("linkedin", models.URLField(blank=True, max_length=255)),
                (
                    "behance",
                    models.URLField(
                        blank=True,
                        default="https://www.behance.net/dearandco",
                        max_length=255,
                    ),
                ),
                (
                    "discord",
                    models.URLField(
                        blank=True,
                        default="https://discord.com/users/magenta_35298",
                        max_length=255,
                    ),
                ),
                (
                    "youtube",
                    models.URLField(
                        blank=True,
                        default="http://www.youtube.com/@DEAR-CO",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
