# Generated by Django 5.0.7 on 2025-08-30 13:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="company_address",
            field=models.CharField(
                blank=True,
                help_text="e.g., 123 Creative Lane, Digital City, 45678",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_background_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Background image for the footer section.",
                max_length=255,
                null=True,
                verbose_name="footer_background",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="google_maps_link",
            field=models.URLField(
                blank=True,
                default="https://share.google/WxcaWdKqqUTiSjRMA",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_image_blur",
            field=models.PositiveIntegerField(
                default=5, help_text="Blur effect on the hero image in pixels (0-20)."
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_image_opacity",
            field=models.PositiveIntegerField(
                default=20, help_text="Opacity of the hero image (0-100)."
            ),
        ),
    ]
