# Generated by Django 5.0.7 on 2025-08-30 17:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Headquarters, Design Studio", max_length=100
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("google_maps_link", models.URLField(max_length=500)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="company_address",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="google_maps_link",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="9846547132",
                help_text="Enter phone number without country code or symbols.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="behance",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="discord",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="enable_dark_mode",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="footer_background_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="footer_background"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="hero_image"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_image_blur",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="hero_image_opacity",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="instagram",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="logo"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="youtube",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
