"""
GameVerse 100 — Complete Production-Grade GDD PDF Generator
Generates a single exhaustive PDF with 100 fully-specified game design documents.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm, cm
from reportlab.lib.colors import (
    HexColor, white, black, Color
)
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, KeepTogether
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate
from reportlab.lib import colors
import os

# ── Palette ──────────────────────────────────────────────────────────────────
C_DEEP    = HexColor("#0D0D1A")
C_DARK    = HexColor("#12122A")
C_NAVY    = HexColor("#1A1A3E")
C_PURPLE  = HexColor("#6C3FC9")
C_VIOLET  = HexColor("#9B59B6")
C_CYAN    = HexColor("#00D4FF")
C_TEAL    = HexColor("#00B4A0")
C_GREEN   = HexColor("#27AE60")
C_YELLOW  = HexColor("#F1C40F")
C_ORANGE  = HexColor("#E67E22")
C_RED     = HexColor("#E74C3C")
C_PINK    = HexColor("#FF6B9D")
C_GOLD    = HexColor("#FFD700")
C_SILVER  = HexColor("#BDC3C7")
C_LIGHT   = HexColor("#ECF0F1")
C_MID     = HexColor("#95A5A6")
C_WHITE   = HexColor("#FFFFFF")

CATEGORY_COLORS = {
    "Arcade":        C_CYAN,
    "Puzzle":        C_PURPLE,
    "Strategy":      C_TEAL,
    "Simulation":    C_GREEN,
    "Sports":        C_ORANGE,
    "Racing":        C_RED,
    "Endless Runner":C_YELLOW,
    "Platformer":    C_PINK,
    "Rhythm":        C_VIOLET,
    "Adventure":     C_GOLD,
    "Survival":      C_RED,
    "Tower Defense": C_TEAL,
    "Idle":          C_GREEN,
    "Educational":   C_CYAN,
    "Memory":        C_PURPLE,
    "Logic":         C_NAVY,
    "Word":          C_ORANGE,
    "Math":          C_YELLOW,
    "Physics":       C_PINK,
    "Experimental":  C_VIOLET,
}

# ── Style Registry ────────────────────────────────────────────────────────────
def build_styles():
    base = getSampleStyleSheet()
    s = {}

    s["cover_title"] = ParagraphStyle(
        "cover_title", fontSize=52, textColor=C_CYAN,
        fontName="Helvetica-Bold", alignment=TA_CENTER,
        spaceAfter=6, leading=58,
    )
    s["cover_sub"] = ParagraphStyle(
        "cover_sub", fontSize=22, textColor=C_LIGHT,
        fontName="Helvetica", alignment=TA_CENTER,
        spaceAfter=4,
    )
    s["cover_tag"] = ParagraphStyle(
        "cover_tag", fontSize=13, textColor=C_MID,
        fontName="Helvetica-Oblique", alignment=TA_CENTER,
        spaceAfter=2,
    )
    s["toc_h1"] = ParagraphStyle(
        "toc_h1", fontSize=11, textColor=C_CYAN,
        fontName="Helvetica-Bold", leftIndent=0,
        spaceAfter=2,
    )
    s["toc_h2"] = ParagraphStyle(
        "toc_h2", fontSize=9.5, textColor=C_LIGHT,
        fontName="Helvetica", leftIndent=12,
        spaceAfter=1,
    )
    s["chapter"] = ParagraphStyle(
        "chapter", fontSize=26, textColor=C_CYAN,
        fontName="Helvetica-Bold", alignment=TA_LEFT,
        spaceBefore=10, spaceAfter=6, leading=32,
    )
    s["game_num"] = ParagraphStyle(
        "game_num", fontSize=11, textColor=C_MID,
        fontName="Helvetica-Bold", alignment=TA_LEFT,
        spaceAfter=2,
    )
    s["game_title"] = ParagraphStyle(
        "game_title", fontSize=22, textColor=C_WHITE,
        fontName="Helvetica-Bold", alignment=TA_LEFT,
        spaceBefore=2, spaceAfter=3, leading=26,
    )
    s["section"] = ParagraphStyle(
        "section", fontSize=13, textColor=C_CYAN,
        fontName="Helvetica-Bold",
        spaceBefore=8, spaceAfter=3, leading=16,
    )
    s["subsection"] = ParagraphStyle(
        "subsection", fontSize=11, textColor=C_YELLOW,
        fontName="Helvetica-Bold",
        spaceBefore=5, spaceAfter=2, leading=14,
    )
    s["body"] = ParagraphStyle(
        "body", fontSize=9.5, textColor=C_LIGHT,
        fontName="Helvetica", leading=14,
        spaceAfter=4, alignment=TA_JUSTIFY,
    )
    s["bullet"] = ParagraphStyle(
        "bullet", fontSize=9.5, textColor=C_LIGHT,
        fontName="Helvetica", leading=13,
        leftIndent=14, firstLineIndent=-8,
        spaceAfter=2,
    )
    s["code"] = ParagraphStyle(
        "code", fontSize=8.5, textColor=C_GREEN,
        fontName="Courier", leading=12,
        leftIndent=10, spaceAfter=3,
        backColor=HexColor("#0A0A15"),
    )
    s["label"] = ParagraphStyle(
        "label", fontSize=9, textColor=C_MID,
        fontName="Helvetica-Bold",
        spaceAfter=1,
    )
    s["category_badge"] = ParagraphStyle(
        "category_badge", fontSize=9, textColor=C_WHITE,
        fontName="Helvetica-Bold", alignment=TA_CENTER,
    )
    s["page_header"] = ParagraphStyle(
        "page_header", fontSize=8, textColor=C_MID,
        fontName="Helvetica", alignment=TA_RIGHT,
    )
    s["note"] = ParagraphStyle(
        "note", fontSize=9, textColor=C_YELLOW,
        fontName="Helvetica-Oblique", leading=13,
        leftIndent=10, spaceAfter=3,
    )
    s["arch_h1"] = ParagraphStyle(
        "arch_h1", fontSize=18, textColor=C_CYAN,
        fontName="Helvetica-Bold",
        spaceBefore=8, spaceAfter=4,
    )
    s["arch_h2"] = ParagraphStyle(
        "arch_h2", fontSize=13, textColor=C_YELLOW,
        fontName="Helvetica-Bold",
        spaceBefore=5, spaceAfter=2,
    )
    s["arch_body"] = ParagraphStyle(
        "arch_body", fontSize=9.5, textColor=C_LIGHT,
        fontName="Helvetica", leading=14,
        spaceAfter=4,
    )
    return s

# ── Helper builders ───────────────────────────────────────────────────────────
def hr(color=C_PURPLE, thickness=0.6):
    return HRFlowable(width="100%", thickness=thickness, color=color, spaceAfter=4, spaceBefore=4)

def sp(h=4):
    return Spacer(1, h)

def colored_table(data, col_widths, header_bg=C_NAVY, row_bg=C_DEEP, alt_bg=HexColor("#0F0F22")):
    t = Table(data, colWidths=col_widths)
    style = [
        ("BACKGROUND", (0,0), (-1,0), header_bg),
        ("TEXTCOLOR",  (0,0), (-1,0), C_CYAN),
        ("FONTNAME",   (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE",   (0,0), (-1,0), 9),
        ("ALIGN",      (0,0), (-1,-1), "LEFT"),
        ("VALIGN",     (0,0), (-1,-1), "TOP"),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [row_bg, alt_bg]),
        ("TEXTCOLOR",  (0,1), (-1,-1), C_LIGHT),
        ("FONTNAME",   (0,1), (-1,-1), "Helvetica"),
        ("FONTSIZE",   (0,1), (-1,-1), 8.5),
        ("GRID",       (0,0), (-1,-1), 0.4, HexColor("#2A2A4A")),
        ("LEFTPADDING",(0,0), (-1,-1), 6),
        ("RIGHTPADDING",(0,0),(-1,-1), 6),
        ("TOPPADDING", (0,0), (-1,-1), 4),
        ("BOTTOMPADDING",(0,0),(-1,-1), 4),
    ]
    t.setStyle(TableStyle(style))
    return t

def badge_table(badges, S):
    """Render a row of colored badges."""
    cells = []
    for text, color in badges:
        p = Paragraph(f"<b>{text}</b>", S["category_badge"])
        cells.append(p)
    widths = [40*mm / len(badges) * len(badges)] * len(badges)
    t = Table([cells], colWidths=[38*mm]*len(badges))
    style_cmds = []
    for i, (_, color) in enumerate(badges):
        style_cmds += [
            ("BACKGROUND", (i,0), (i,0), color),
            ("ROUNDEDCORNERS", [3]),
        ]
    style_cmds += [
        ("ALIGN", (0,0), (-1,-1), "CENTER"),
        ("VALIGN", (0,0), (-1,-1), "MIDDLE"),
        ("TOPPADDING", (0,0), (-1,-1), 3),
        ("BOTTOMPADDING", (0,0), (-1,-1), 3),
        ("LEFTPADDING", (0,0), (-1,-1), 4),
        ("RIGHTPADDING", (0,0), (-1,-1), 4),
    ]
    t.setStyle(TableStyle(style_cmds))
    return t

# ── Game Data ─────────────────────────────────────────────────────────────────
GAMES = [
  # (num, title, genre, category, difficulty, color_key,
  #  theme, loop, controls, scoring, levels_desc,
  #  powerups, obstacles, audio_desc, visual_desc,
  #  hud_elements, accessibility_notes, storage_keys, edge_cases, qa_notes)

  (1,"NeonBlitz","Arcade Shooter","Arcade","Medium",C_CYAN,
   "Neon-drenched cyberpunk city skyline at night. Player pilots a hoverbike through laser-grid canyons.",
   "Player moves horizontally across a parallax scrolling city. Shoot incoming drones, dodge barriers, collect power capsules. Wave-based enemy spawns increase in density every 30 seconds. Chain kills multiply score.",
   "Desktop: Arrow keys / WASD to move, Space to shoot, Shift for boost. Mouse: click to shoot. Touch: virtual joystick left, tap right to fire. Controller: left stick move, A shoot, RT boost.",
   "Base kill: 100pts. Chain 5 kills: x2 multiplier. Chain 10: x3. Survival bonus: +500 per minute alive. Wave clear bonus: 1000 * wave_number. High score stored locally.",
   "Tutorial (wave 1-3): single-file drones, slow projectiles. Easy (4-10): dual-column, slight homing. Medium (11-20): shield drones, splitting bullets. Hard (21-35): boss mini-drones, EMP pulses. Expert (36+): endless adaptive AI.",
   "Shield Bubble (5s immunity), Rapid Fire (3s 3x fire rate), Time Warp (0.5x game speed 4s), Magnet (auto-collect pickups 8s), Overdrive (score x4 6s).",
   "Standard Drone (linear), Shield Drone (2-hit), Splitter (2 children on death), EMP Tower (disables boost), Turret Wall (rapid fire barrage), Boss Carrier (spawns 8 drones).",
   "Synthwave 120BPM background track. Laser fire: high-pitched zap. Explosion: layered bass boom. Power-up collect: ascending arpeggio. Chain multiplier: escalating synth chord. Game over: descending minor chord.",
   "Dark navy/electric blue background with parallax neon grids. Sprite outlines glow cyan/pink. Explosion particles: orange/white sparks. HUD font: monospace glowing white. Art style: flat vector + glow shaders.",
   "Score (top-center), Lives x3 (top-left hearts), Wave counter (top-right), Boost meter (bottom-left arc bar), Multiplier (center-top badge), Mini-map strip (bottom).",
   "Colorblind mode replaces color-coded enemy types with distinct shape silhouettes. All UI controls keyboard-navigable. Reduced motion hides parallax scroll. Subtitles for audio cues.",
   "neonblitz_highscore, neonblitz_wave, neonblitz_achievements, neonblitz_settings",
   "Chain counter reset on death must not persist across lives. EMP during power-up active state must queue, not stack. Touch joystick must clamp to screen bounds.",
   "Shoot 500 enemies (accuracy %), survive wave 20, test colorblind palette, verify localStorage on private-mode browsers, 60 FPS on mid-range Android."),

  (2,"HexCipher","Puzzle","Puzzle","Hard",C_PURPLE,
   "Ancient alien vault deep in an ice moon. Hexagonal tiles pulse with alien bioluminescence. Player is an AI archaeologist decoding alien locks.",
   "Rotate hexagonal tile rings to align color sequences. Each puzzle is a concentric set of hex rings. Correct alignment unlocks the next ring outward. Mis-alignment adds a time penalty. Solve all rings to clear the level.",
   "Desktop: click-drag ring to rotate, scroll wheel fine-tune. Keyboard: Tab select ring, Left/Right arrow rotate, Enter confirm. Touch: swipe arc on ring to rotate.",
   "Base solve: 500pts per ring. Time bonus: max 300pts decayed per 10s. Hint penalty: -100pts each. Perfect solve (no hints): +1000 bonus. Combo: consecutive perfect solves x1.5.",
   "L1-5: 2-ring, 4-colour. L6-12: 3-ring, 6-colour. L13-20: 4-ring, 8-colour. L21-30: 4-ring, rotating tiles mid-solve. L31+: 5-ring, colour-shifting tiles, timed.",
   "Freeze Time (10s pause), Highlight Hint (show one correct position), Ring Lock (auto-align one ring), Colour Key (reveal colour map 5s), Undo Last (reverse last rotate).",
   "Decoy Tiles (show wrong colour briefly), Gravity Shift (tiles rotate randomly every 15s), Mirror Lock (ring rotates opposite), Shroud (dims outer ring).",
   "Ambient crystalline drone. Ring rotate: soft ceramic click. Correct align: harmonic chime. Wrong align: low thud. Level complete: majestic alien fanfare. Hint used: soft warble.",
   "Ice-blue/teal/purple hex tiles on dark void background. Correct tiles emit white inner glow. Alien runes animate on outer border. Font: serif alien-inspired. Parallax star-field background.",
   "Level number (top-left), Timer (top-center countdown), Score (top-right), Hint count (bottom-left gems), Ring status dots (bottom-center), Undo button (bottom-right).",
   "High-contrast mode for colourblind: pattern fill replaces colour. Screen reader announces ring alignment percent. Reduced motion disables tile pulse animation.",
   "hexcipher_highscore, hexcipher_level, hexcipher_perfect_count, hexcipher_settings",
   "Concurrent finger touches on different rings must be isolated. Ring rotation animation must complete before re-input. Level seed must be deterministic from level number.",
   "Solve all 30 base levels, verify hint deduction, test ring lock power-up, validate timer pause on tab-switch, test on iOS Safari touch."),

  (3,"GravityRacer","Racing","Racing","Medium",C_RED,
   "Low-gravity asteroid belt circuit races. Ships navigate floating rock corridors with plasma jet trails in a deep-space environment.",
   "Player steers a gravity-assist ship through curved asteroid corridors. Slingshot around large asteroids for speed boosts. Avoid debris. Three laps per race. Rivals use rubber-band AI.",
   "Desktop: Left/Right arrows steer, Up thrust, Down brake/reverse. Mouse: hold left-click direction. Touch: tilt controls or on-screen arrows. Controller: left-stick steer, RT thrust.",
   "Position at finish: P1=1000, P2=750, P3=500, P4=250. Lap record bonus: +300. No-collision bonus: +200. Slingshot count bonus: +50 each. Fastest lap time stored.",
   "Circuit 1: single-loop, 3 wide corridors. C2: tight S-bends, 2 debris fields. C3: gravity wells, 4 rivals. C4: split paths, asteroid storms. C5: full dynamic track, 5 rivals, time limit per lap.",
   "Nitro Boost (3s x2 speed), Gravity Shield (deflect debris 5s), Magnet Slingshot (double slingshot radius 8s), Ghost Mode (pass through rivals 4s), Repair Kit (restore 50% hull).",
   "Debris Boulder (random trajectory), Rival Racer (rubber-band AI), Gravity Well (pull ship off-course), Plasma Mine (drops from rivals), Asteroid Storm (50% corridor blocked).",
   "Electronic rock race music 140BPM. Engine hum (pitch changes with speed). Slingshot: deep whoosh. Collision: metallic crunch. Nitro: high-pitched jet burst. Finish: triumphant brass sting.",
   "Dark space blue with glowing asteroid textures. Ship trails: gradient magenta-to-white. HUD transparent glass look. Rival ships distinct colour-coded. Speed lines on boost. Parallax nebula background layers.",
   "Speed dial (bottom-left), Hull integrity bar (bottom-right), Lap counter (top-left), Position (top-right P1/P5 badge), Rival map strip (top-center mini), Boost meter (center-bottom arc).",
   "Tilt controls can be disabled for accessibility. All rivals distinguishable by shape+colour. Collision warnings via screen flash + audio tone. Keyboard-only fully playable.",
   "gravityracer_bestlap, gravityracer_circuit_stars, gravityracer_achievements, gravityracer_settings",
   "Slingshot assist must not stack with Magnet power-up multiplicatively. Rival rubber-band must not teleport visibly. Tilt controls must disable on desktop.",
   "Complete all 5 circuits, verify rival AI rubber-band, test tilt disable, 60FPS asteroid storm, localStorage circuit star persistence."),

  (4,"PixelFarm","Simulation","Simulation","Easy",C_GREEN,
   "Charming pixel-art countryside. Player inherits a rundown farm and transforms it into a thriving agricultural estate through seasons.",
   "Plant crops, water them, harvest at maturity, sell at market. Manage soil health, seasons, pests. Unlock animals, buildings, automation tools. Day-night cycle advances per action count.",
   "Desktop: WASD move avatar, E interact, click tiles. Touch: tap tile to interact, swipe to move. Keyboard: full navigation, Enter confirm, Esc menu.",
   "Crops: base value x quality multiplier. Quality: 1-5 stars based on soil health and watering timing. Market day bonus: x1.5. Export contracts: fixed price + bonus. Season crop bonus: x2.",
   "Year 1: basic 4 crops. Y2: animals + market. Y3: seasonal events + exports. Y4: automation tools. Y5: farm festival + expansion plots. Endless: prestige system.",
   "Fertilizer Boost (x2 yield this harvest), Rain Charm (auto-water all crops 1 day), Pest Shield (protect from bugs 3 days), Market Rush (x2 sell price today), Speed Plow (instant till all).",
   "Crop Blight (reduces yield 50%), Pest Swarm (destroys 1 crop tile), Drought (no growth without manual water), Flood (delays harvest 1 day), Heatwave (reduces quality 1 star).",
   "Gentle folk acoustic guitar loop. Planting: soft thud. Watering: splashing. Harvest: satisfying pop. Market bell: cheerful ding. Rain: ambient patter. Night: cricket ambience.",
   "16px pixel art. Bright pastel palette: green fields, brown soil, yellow wheat. Seasons shift colour palette (spring pink blossoms, summer vivid, autumn gold, winter snow overlay). Smooth pixel scrolling.",
   "Day counter (top-left), Gold balance (top-right coin icon), Season indicator (sun/snowflake), Energy bar (top-center), Crop growth status (hover tooltip), Mini-map (corner).",
   "Text descriptions for all crops. High contrast soil state indicators. Screen reader announces season changes. Keyboard-complete interaction model.",
   "pixelfarm_gold, pixelfarm_day, pixelfarm_unlocks, pixelfarm_layout, pixelfarm_settings",
   "Simultaneous crop maturity notifications must batch. Day advance mid-action must not skip events. Season transition must save before proceeding.",
   "Full Year 5 run, pest event triggers, market price algorithm, seasonal palette switch, mobile touch accuracy on 4-inch screen."),

  (5,"ShadowHopper","Platformer","Platformer","Medium",C_PINK,
   "Ink-wash silhouette world where a shadow sprite hops between floating lanterns, ancient temples, and paper-fold forests.",
   "Player jumps between platforms, flips gravity at shadow gates, collects ink orbs, avoids light beams (which dissolve the shadow). Wall-jump and double-jump mechanics. Boss at every 5th level.",
   "Desktop: Arrow/WASD move+jump, S/Down flip gravity, Z wall-cling. Touch: left/right tap sides, tap center jump, swipe down flip. Controller: D-pad, A jump, B flip.",
   "Ink orb: 10pts. Perfect landing (centre of platform): +5. Chain jumps (no ground touch): x1.2 per jump. Boss kill: 5000pts. Time bonus: level_time_limit minus elapsed * 10.",
   "L1-5: intro platforms, single gravity flip. L6-15: moving platforms + light beams. L16-25: chain-gravity puzzles. L26-35: wall-cling + laser grids. L36-45: boss every 5. L46+: procedural.",
   "Ink Burst (destroy all enemies on screen), Phase Shift (pass through 1 platform), Speed Shadow (2x move speed 5s), Double Ink (orbs worth x2 8s), Gravity Anchor (slow gravity flip 4s).",
   "Light Beam (instant kill contact), Moving Platform (varying speeds), Lantern Sentry (rotates light cone), Paper Crane (flies in arcs), Mirror (reflects light beam), Boss Lantern Lord.",
   "Taiko drum loop for movement energy. Jump: hollow drum strike. Gravity flip: deep bass reverb. Light contact: sharp shriek. Ink orb: soft bell. Boss intro: orchestral taiko build.",
   "High-contrast black-on-white ink wash. Platforms: brushstroke edges. Background: three parallax layers of grey-wash mountain silhouettes. Player: pure black silhouette with white eye. Light beams: yellow with bloom glow.",
   "Lives (top-left ink drops), Score (top-right), Level (top-center), Ink meter (bottom-left for special), Platform stability hints (subtle arrows on unstable platforms).",
   "Silhouette art is inherently contrast-accessible. Pattern-coded hazards (light beams striped). Keyboard-complete. Reduced motion: no parallax scroll.",
   "shadowhopper_highscore, shadowhopper_level, shadowhopper_achievements, shadowhopper_settings",
   "Gravity flip mid-jump must calculate correct trajectory. Wall-cling must not stick to moving platforms incorrectly. Boss health bar must not overflow HUD.",
   "Wall-jump angle test, gravity flip physics, boss AI sequence, procedural level seeding, 60FPS mobile, light beam rendering overlap."),

  (6,"BeatForge","Rhythm","Rhythm","Hard",C_VIOLET,
   "Futuristic music lab. Player forges beats by hitting falling note anvils in a glowing foundry. Musical genre unlocks new zones.",
   "Notes fall in 4-6 lanes. Hit on beat marker: Perfect/Good/Miss rating. Hold notes for sustained tones. Chord bursts hit multiple lanes simultaneously. BPM increases across songs.",
   "Desktop: D/F/J/K/L keys for 5 lanes. Mouse: click lanes. Touch: tap lanes. Controller: face buttons + shoulders for 6 lanes.",
   "Perfect: 300pts, Good: 150pts, Miss: 0, breaks streak. Streak x multiplier (max x8 at 50 streak). Song clear bonus: 2000pts. Full combo: 5000pts bonus. S-rank: all Perfects.",
   "Beginner: 4 lanes, 80BPM, single notes. Intermediate: 5 lanes, 120BPM, holds. Advanced: 6 lanes, 150BPM, chords. Expert: 6 lanes, 180BPM, hidden notes. Master: custom BPM, complex patterns.",
   "Note Fever (x2 score 10s), Slow Motion (0.7x speed 8s), Auto-Hit (one lane auto 5s), Shield (no miss penalty 5s), Double Perfect (all hits count as Perfect 8s).",
   "Speed Note (2x fall speed), Fake Note (punishes wrong hit), Ghost Note (semi-transparent, must hit), Bomb Note (miss = lose 500pts), Wall Note (blocks lane until cleared).",
   "Procedurally timed note sounds sync to song. Miss: dull thunk. Perfect: resonant anvil ring. Chord: harmonic cluster. Fever mode: adds reverb to all sounds. Three unique tracks per genre.",
   "Dark foundry aesthetic. Glowing lava-orange lanes with steel borders. Notes: genre-themed (crystal for pop, flame for rock, cloud for electronic). Background: parallax molten metal + gears. HUD: industrial LCD panels.",
   "Lane labels (D/F/J/K), Combo streak (center glow counter), Score (top-right), HP bar (top-left), BPM indicator (bottom), Fever gauge (vertical bar right side).",
   "Keyboard labels visible on lanes always. Audio-beat flash for deaf users. Calibration offset setting for audio latency. Reduced motion: no parallax only.",
   "beatforge_highscore_songname, beatforge_unlocked_songs, beatforge_best_rank, beatforge_settings",
   "Audio latency must be compensatable. Note spawn timing must be deterministic per song. Chord detection window must not overlap adjacent lanes.",
   "All 5 difficulty tiers, full combo test, audio latency calibration, touch lane accuracy on 6-inch screen, no dropped notes at 180BPM."),

  (7,"CrystalMaze","Puzzle","Puzzle","Medium",C_TEAL,
   "Underground crystal cavern. Player guides a light beam through maze of crystal prisms to illuminate ancient seals.",
   "Player places mirrors and prisms on a grid to redirect a light beam from source to target seal. Limited pieces per level. Multiple beams from level 15. Timed mode from level 25.",
   "Desktop: click empty cell to place piece, right-click rotate, drag to reposition. Keyboard: arrow keys navigate grid, Enter place, R rotate, Del remove. Touch: tap place, two-finger rotate.",
   "Seal lit: 500pts. All seals lit: 2000 bonus. Pieces used efficiency: (max_pieces - used) * 100. Time bonus: remaining_seconds * 20. Hint penalty: -200 each.",
   "L1-8: single beam, 3 prisms. L9-16: two beams, colour mixing. L17-24: coloured seals (need colour match). L25-32: timed + beam splitters. L33+: dynamic crystals (rotate every 5s).",
   "Crystal Reveal (show one placement), Beam Trace (show full path 3s), Extra Piece (add one mirror), Freeze Crystals (pause dynamic rotation 10s), Colour Filter (remove colour constraint 1 use).",
   "Dark Crystal (absorbs beam), Prism Wall (scatters beam randomly), Colour Blocker (changes beam colour), Time Crystal (speeds up timed rotation), Mirror Lock (can't move once placed).",
   "Ethereal ambient hum. Beam emit: sustained tone. Prism hit: crystal ting. Seal lit: resonant hum chord. All seals: triumphant crystal fanfare. Wrong path: low dissonant tone.",
   "Deep cave navy background with bioluminescent crystal textures. Beam: bright laser with glow trail in beam colour. Prisms: translucent faceted geometry. Seals: ornate circular runes. Grid lines: subtle dark blue.",
   "Level (top-left), Pieces remaining (top-right icons), Timer (top-center, red when < 10s), Seals status (bottom row), Undo button, Hint gem count.",
   "Beam colour also indicated by path width pattern. Grid navigable entirely by keyboard. Screen reader announces seal status. High-contrast outline mode.",
   "crystalmaze_highscore, crystalmaze_level, crystalmaze_hints_used, crystalmaze_settings",
   "Beam must recalculate on every piece move. Colour mixing logic (red+blue=purple) must be consistent. Dynamic crystal rotation must not interrupt solve in progress for placed pieces.",
   "All 33 levels, colour-mix beam logic, dynamic crystal timing, undo stack integrity, beam render at 60FPS on 100-cell grids."),

  (8,"TowerTide","Tower Defense","Tower Defense","Hard",C_TEAL,
   "Ocean fortress under siege. Player builds coral reef and submarine towers to defend an underwater city from mutant sea creature waves.",
   "Place towers on seabed grid before wave. Earn kelp-credits per kill. Upgrade towers 3 tiers. Sell at 70% refund. Boss waves every 5. Earn bonus towers by completing wave bonus objectives.",
   "Desktop: click grid to place/upgrade, right-click to sell, keyboard hotkeys for tower types. Touch: tap grid, bottom-bar tower selector. Keyboard: QWERT for towers, click grid.",
   "Kill credit: based on enemy HP. Wave survival: 500pts. No leak (no enemy passes): 1000 bonus. Speed run bonus: (par_time - actual_time) * 50. Tower upgrade efficiency award.",
   "W1-5: linear path, basic creatures. W6-10: branching paths. W11-15: flying creatures. W16-20: armoured crabs + air. W21-25: boss + minions. W26-30: regenerating enemies. W31+: endless prestige.",
   "Depth Charge (area damage all enemies on-screen), Tidal Wave (slows all 50% 10s), Sonar Pulse (reveals invisible enemies), Coral Barrier (temporary wall blocks path 8s), Power Current (all towers +50% fire rate 10s).",
   "Jellyfish Swarm (fast, low HP), Armoured Crab (high HP, slow), Eel Flyer (aerial, bypasses ground towers), Regenerator (regains HP if not killed quickly), Giant Angler Boss (multi-HP bar).",
   "Oceanic orchestral loop. Tower shoot: sonar ping. Explosion: underwater muffled boom. Enemy breach: alarm klaxon. Wave start: depth charge thud. Victory: coral reef symphony jingle.",
   "Dark teal ocean floor. Bioluminescent tower designs. Enemy sprites: stylised sea creatures with shimmer. Path: sandy seafloor with coral edges. Water surface parallax top layer. Particle bubbles on explosions.",
   "Lives (anchor icons), Credits (kelp icon), Wave counter, Wave timer countdown, Tower preview panel (left), Enemy wave preview (right panel), Speed toggle (1x/2x).",
   "Tower placement highlighted accessible via keyboard grid nav. Enemy type icons have shape+pattern differentiation. Speed toggle accessible. Screen reader wave announcement.",
   "towertide_highwave, towertide_gold_earned, towertide_unlock_towers, towertide_settings",
   "Path-finding must recalculate on barrier tower placement. Flying enemies must ignore ground-only towers. Boss HP bar scaling on prestige must cap gracefully.",
   "Path recalculation stress test, aerial path logic, 50-enemy wave 60FPS, sell refund calculation, prestige score reset with stat preservation."),

  (9,"WordWeave","Word","Word","Easy",C_ORANGE,
   "Ancient library of interwoven language vines. Letters hang from glowing vines, player weaves them into words to unravel mystery scrolls.",
   "Letter tiles on a hex grid. Player swipes connected letters to form words. Minimum 3 letters. Longer words score more. Themed word sets per scroll. 90-second rounds. Daily challenge mode.",
   "Desktop: click-drag mouse to connect letters. Keyboard: type letters directly (auto-connects adjacent). Touch: swipe to connect letters.",
   "3 letters: 100pts, 4: 300pts, 5: 600pts, 6: 1000pts, 7+: 1500pts + rarity bonus. Double-letter tile: x2 that letter's value. Time bonus: 10pts per second remaining. Daily streak: +500.",
   "Scroll 1-5: common 3-4 letter words. S6-10: 5-letter, themed (nature). S11-15: 6-letter, compound words. S16-20: 7-letter, rare vocabulary. S21+: timed endless, rare bonus tiles.",
   "Letter Bloom (all tiles give double value 15s), Word Root (shows 1 valid word hint), Time Vine (add 20 seconds), Shuffle (randomise grid), Wildcard Leaf (any letter substitute).",
   "Frost Tile (must use adjacent warm tile first), Thorn Tile (blocks swipe through it), Locked Tile (can't use until adjacent word formed), Decay Tile (disappears after 5s if unused).",
   "Forest ambient with light birdsong. Letter select: soft leaf rustle. Word submit valid: chime cascade. Word invalid: dull thud. Long word: triumphant forest horn. Timer warning: accelerating cricket chirp.",
   "Parchment-brown hex grid with emerald letter tiles. Vine animations between connected letters. Background: parallax layered forest with dust motes. Font: serif elegant on tiles. Colour-glow on valid word path.",
   "Score (top-right), Timer bar (top full-width gradient drain), Words found count, Current word display (bottom), Power-up bar (bottom), Streak indicator (left badge).",
   "Swipe gesture also triggerable by keyboard. All letter-tile states (frozen, locked) have pattern fill + icon. Screen reader announces word found with letter count.",
   "wordweave_highscore, wordweave_words_found, wordweave_daily_streak, wordweave_settings",
   "Dictionary must be bundled offline (min 10,000 words). Invalid word animation must not lock input. Wildcard must not allow invalid combinations.",
   "10,000-word offline dictionary check, swipe detection accuracy, wildcard rules, daily streak rollover at midnight, 60FPS on hex grid redraws."),

  (10,"QuantumDrift","Experimental","Experimental","Hard",C_VIOLET,
   "Subatomic particle lab. Player navigates a quantum particle through probability clouds, collapsing wave functions strategically to clear paths.",
   "Player exists in superposition: move both left and right simultaneously until observation. Click to collapse to one path. Obstacles trigger auto-observation. Collect quantum tokens before collapsing. Score based on tokens collected across both states.",
   "Desktop: Left/Right arrows move both particles, Space collapse to chosen side, click desired particle to collapse. Touch: swipe to move, tap particle to observe. Keyboard: Tab switch focus particle, Enter collapse.",
   "Token in superposition (collected by both): 200pts each. Token after collapse: 100pts. Fewer collapses used: efficiency bonus up to 2000pts. Level clear: 1000pts. Perfect run (max tokens): x2 multiplier.",
   "L1-5: single obstacle, forced collapse. L6-12: branching paths, optional collapse. L13-20: three-state particles. L21-28: entangled pairs (both must collect). L29+: probability storms, time-limited.",
   "Probability Boost (extend superposition window 5s), Entanglement (link two tokens so collecting one gives other free), Observer Shield (next observation doesn't count toward limit), Tunnel Effect (pass through one obstacle), Wave Amplifier (double token values 10s).",
   "Observation Wall (forces collapse on contact), Decoherence Field (reduces superposition time 3s), Anti-particle (cancels collected token), Quantum Eraser (removes last collected token), Probability Storm (random auto-observations).",
   "Electronic ambient with quantum-physics-inspired sine wave tones. Superposition hum: dual-layered stereo pan. Collapse: single sharp click + resonance decay. Token collect: phase-shifting bell. Probability storm: white noise burst.",
   "Dark void background with probability wave overlays (translucent sine curves). Particles: glowing orbs (left=cyan, right=magenta). Tokens: rotating quantum symbols. Obstacles: geometric crystalline forms with danger glow.",
   "Superposition timer (center arc), Collapse count (top-left quantum symbol), Score (top-right), Token collection status (bottom icons), Current level / total levels.",
   "Dual-particle mechanic fully keyboard navigable. Particle states announced via screen reader. High-contrast particles (shape differentiation). Reduced motion: no probability wave animation.",
   "quantumdrift_highscore, quantumdrift_level, quantumdrift_collapses_used, quantumdrift_settings",
   "Simultaneous movement of both particles must be pixel-perfect mirror. Collapse must be atomic (no mid-frame state). Entanglement tokens must not double-count.",
   "Superposition physics correctness, entanglement pair logic, probability storm random seed, collapse animation at 60FPS, touch target size for particle tap."),
]

# Additional 90 games condensed data
GAMES_EXT = [
  (11,"MathBlaster3D","Math","Math","Easy",C_YELLOW,
   "Space academy. Student pilots solve math equations to fire cannons and destroy incoming number asteroids.",
   "Equations appear. Player types/selects correct answer. Correct: fires cannon destroying asteroid. Wrong: asteroid hits shield. 60s rounds. Difficulty auto-adjusts.",
   "Desktop: keyboard type answer, Enter submit. Touch: on-screen numpad. Mouse: click numpad.",
   "Correct fast (<3s): 200pts. Correct slow: 100pts. Wrong: -50pts. Streak 5: x2. Accuracy bonus: (correct/total)*500 at round end.",
   "Addition/subtraction. Multiplication. Mixed operations. Algebra basics. Word problems. Timed expert mode.",
   "Double Points (20s), Time Stop (5s), Skip Problem, Auto-Correct (one use), Mega Blast (clears 5 asteroids).",
   "Giant Asteroid (needs 3 correct), Splitter (wrong answer splits into 2), Speed Asteroid (faster trajectory), Armoured (need chain of 3 corrects), Boss Equation Chain.",
   "8-bit space jingle. Correct answer: laser zap. Wrong: buzzer. Streak: ascending notes. Level up: triumphant fanfare. Asteroid explode: crunch.",
   "Retro pixel space art. Equations on asteroids in bold LCD font. Background: star parallax. Cannon: chunky metal sprite. Explosion: pixel burst. Palette: navy, yellow, orange.",
   "Score, Shield HP, Timer, Streak badge, Current equation large center, Accuracy %, Lives.",
   "Large numpad for motor accessibility. Font size adjustable. All sounds have visual flash equivalent. Keyboard-complete.",
   "mathblaster_highscore, mathblaster_level, mathblaster_accuracy, mathblaster_settings",
   "Answer validation must trim whitespace. Algebra mode must show step-by-step option. Timer pause on focus-loss.",
   "All 6 difficulty tiers, accuracy calc, algebra parser, 60FPS particle, mobile numpad layout."),

  (12,"EcoBalance","Simulation","Simulation","Medium",C_GREEN,
   "Living planet management. Player balances species populations, climate, and resources to maintain planetary biodiversity.",
   "Add/remove species, adjust climate dials, manage pollution. Ecosystem web shows cause-effect. Monthly simulation tick. Crisis events require rapid response.",
   "Desktop: click ecosystem nodes, sliders for climate. Touch: tap nodes, pinch zoom. Keyboard: Tab navigate controls, Enter/Space adjust.",
   "Biodiversity index maintained above 70%: +100/month. Species extinction: -500. Crisis resolved: 1000pts. 10-year run high score.",
   "5 species, stable climate. Add predators. Invasive species. Industry vs. nature. Climate tipping points. Planetary restoration.",
   "Rain Seeder, Pollution Filter, Species Revival, Trophic Cascade Boost, Climate Stabiliser.",
   "Drought, Invasive Species, Industrial Pollution, Overpopulation, Extinction Cascade.",
   "Nature documentary orchestral. Rain: ambience. Extinction: mournful chord. Crisis alert: urgent strings. Balance peak: serene harmonic resolve.",
   "Living planet illustration art. Lush greens/blues for healthy, browns/greys for crisis. Species icons: stylised flat animals. Climate dials: analogue gauge UI. Seasonal parallax sky.",
   "Biodiversity index gauge, Species count, Climate stability bar, Pollution level, Month/Year, Crisis alert panel.",
   "Colour + icon for all ecosystem states. Screen reader announces crisis. Keyboard navigation of all sliders. Reduced motion: static ecosystem illustration.",
   "ecobalance_score, ecobalance_year, ecobalance_extinctions, ecobalance_settings",
   "Cascading extinction must not infinite-loop. Climate dial bounds must clamp. Invasive species event must fire max once per cycle.",
   "Extinction cascade stress test, climate bounds, 100-year run stability, species count overflow, mobile slider precision."),

  (13,"RuneChaser","Adventure","Adventure","Medium",C_GOLD,
   "Ancient rune-hunter explores procedurally generated stone temples, collecting lost runes before traps seal the temple.",
   "Top-down dungeon exploration. Collect runes, dodge pressure-plate traps, solve door locks, fight stone guardians. Each temple generated from seed. 10-minute timer per temple.",
   "Desktop: WASD move, E interact, Space dash, 1-4 use items. Touch: virtual joystick + action buttons. Keyboard-complete.",
   "Rune collect: 200pts. Guardian defeat: 500pts. Temple cleared: 2000pts. Time remaining * 50. No-damage bonus: 1000pts. Rune combo (all runes): x3.",
   "Tutorial temple: 5 runes, basic traps. 3-room temple. Multi-floor dungeon. Guardian gauntlet. Boss temple. Endless random.",
   "Speed Rune (2x move 8s), Trap Sight (show all trap locations 15s), Guardian Stun (freeze guardians 5s), Rune Magnet (auto-collect nearby), Shield Glyph (block one hit).",
   "Pressure Plate, Rolling Boulder, Spike Floor, Stone Guardian (melee), Rune Sentinel (ranged), Collapsing Floor, Boss Golem.",
   "Mystical orchestral. Footstep: stone echo. Trap trigger: stone scrape. Guardian roar: deep growl. Rune collect: harmonic tone. Temple seal: cathedral organ low note.",
   "Stone texture top-down art. Torchlit amber corridors. Runes: glowing blue symbols. Traps: floor markings. Guardians: imposing stone sprites. Parallax torchlight flicker overlay.",
   "HP (stone hearts), Timer (torchlight drain), Rune count, Item slots (4), Map partial reveal, Dash cooldown arc.",
   "All traps have audio+visual cue. Screen reader announces room entry. Keyboard complete movement. High-contrast rune outlines.",
   "runechaser_highscore, runechaser_temples, runechaser_runes, runechaser_settings",
   "Procedural generation must guarantee solvable paths. Guardian pathfinding must not clip through walls. Timer must pause on pause screen.",
   "50 temple stress test for solvability, guardian pathfinding, trap trigger detection, map reveal sync, iOS touch joystick."),

  (14,"NeuralNet","Logic","Logic","Hard",C_PURPLE,
   "AI training facility. Player connects neural network nodes by drawing synapse paths to route signals from input to output layer.",
   "Drag to connect nodes. Signal flows left-to-right. Activation threshold must be met. Wrong connections cause signal loss. Solve in minimal connections for bonus.",
   "Desktop: click-drag between nodes. Keyboard: Tab node select, Enter connect. Touch: tap+drag.",
   "Signal output strength: base 1000pts. Connection efficiency: (optimal_connections / used) * 500. Speed bonus: seconds_remaining * 30. Perfect route: 2000 bonus.",
   "3 nodes, direct path. Activation gates. Multi-layer. Feedback loops. Noise injection. Time-pressure auto-rewiring.",
   "Boost Signal (2x signal strength one path), Node Bridge (bypass one layer), Noise Filter (remove one noise node), Auto-Optimizer (suggest best path), Signal Amplifier (all paths +20% strength).",
   "Noise Node (degrades signal), Gate Node (requires specific input pattern), Firewall (blocks connection), Decay Node (signal weakens over path), Inverter Node (flips signal).",
   "Electronic ambient. Node connect: soft click. Signal flow: pulsing tone. Correct output: synthesiser chord. Wrong: static burst. Level clear: digital fanfare.",
   "Dark tech background with glowing circuit board lines. Nodes: coloured circles by layer. Connections: animated pulsing lines. Signal strength visualised as brightness. Clean monospace UI.",
   "Signal strength meter, Connection count, Level indicator, Optimal count hint, Timer (advanced levels), Score.",
   "Node colours also shape-coded. Keyboard path navigation complete. Screen reader announces signal routing. High-contrast mode.",
   "neuralnet_highscore, neuralnet_level, neuralnet_optimal_count, neuralnet_settings",
   "Circular connections must detect and prevent infinite loops. Signal strength calculation must be deterministic. Connection drag must snap to nearest node.",
   "Loop detection algorithm, signal propagation precision, 20-node grid 60FPS, snap accuracy, keyboard path nav."),

  (15,"GalacticGardener","Idle","Idle","Easy",C_GREEN,
   "Deep-space greenhouse. Player grows exotic alien flora that passively generates stardust currency. Automates and upgrades over cosmic time.",
   "Plant seeds, water periodically, collect stardust. Unlock auto-waterers. Upgrade plants for multipliers. Prestige system resets garden but grants cosmic boosters.",
   "Desktop/Touch: click to water, click to collect, click upgrades. Keyboard: Tab/Enter navigate shop.",
   "Stardust per second (SPS) as main metric. Total stardust earned as score. Prestige multiplier preserved. Milestone bonuses at each new plant species.",
   "5 plant types. 10 upgrades. Auto-collect. Prestige. Rebirth. Cosmic mega-plants.",
   "Stardust Storm (10x gain 30s), Solar Flare (instant 1hr worth), Seed Burst (plant 5 instantly), Growth Serum (2x SPS 5min), Cosmic Rain (all plants level up).",
   "Space Fungi (reduces one plant's output), Meteor Strike (destroys one plant, must replant), Radiation (halves production until fixed), Wilt Event (manual water needed), Void Drain (steals 10% stardust).",
   "Gentle space ambient. Watering: trickle. Collect: stardust sparkle. Upgrade: synth chime. Prestige: cosmic horn. Idle tick: soft pulse.",
   "Space greenhouse: dark star background, glowing plants in vivid alien colours. Art style: flat vector with glow. UI: glass panel dark HUD. Parallax nebula layers.",
   "Total stardust (top), SPS display, Plant grid, Upgrade shop panel, Prestige button + counter, Last-collection timer.",
   "Idle games must function without interaction. All buttons keyboard-accessible. Screen reader SPS announcements. Reduced motion: no plant sway.",
   "galacticgardener_stardust, galacticgardener_sps, galacticgardener_prestige, galacticgardener_unlocks, galacticgardener_settings",
   "Offline production must calculate correctly on tab return. Prestige must not lose progress data. Plant destruction event must not reduce stardust below 0.",
   "Offline production calc, prestige loop, plant destruction floor, upgrade multiplier stack, mobile tap precision."),

  (16,"FusionChef","Simulation","Simulation","Medium",C_ORANGE,
   "Intergalactic fusion restaurant. Player cooks alien dishes by combining ingredients in correct sequence under time pressure. Restaurant management layer.",
   "Orders arrive with dish and time limit. Player selects ingredients in recipe order, cook, serve. Earn credits, upgrade kitchen equipment. Handle multiple orders simultaneously.",
   "Desktop: keyboard hotkeys for ingredients+equipment, click dishes. Touch: tap ingredient conveyor, swipe to serve. Keyboard: 1-9 ingredient keys, Enter serve.",
   "Perfect serve (on time): 500pts. Late: 200pts. Wrong dish: -100pts, customer leaves. Combo (5 correct): x2. All tables served: 1500 bonus.",
   "2 recipes, 1 table. 5 recipes, 3 tables. Multi-order overlap. Rush hour. Chef challenge. Endless dinner service.",
   "Speed Boost (2x cook time 15s), Order Preview (see next 3 orders), Auto-Prep (one ingredient auto-added), Tip Surge (double tips 30s), Kitchen Robot (one order auto-served).",
   "Impatient Customer (shorter timer), Wrong Order (sabotages one order), Kitchen Fire (stalls equipment 5s), Ingredient Shortage (one item unavailable 10s), Health Inspector (must be 100% accurate).",
   "Jazz kitchen ambience. Cooking sizzle. Serve: satisfying ding. Wrong order: buzzer. Level up: restaurant applause. Fire alarm: urgent klaxon.",
   "Isometric kitchen art. Bright food colours against dark metal surfaces. Order tickets on top rail. Ingredient icons: vibrant round icons. Customer sprites: alien races. Serving counter parallax depth.",
   "Order queue (top), Timer per order (colour draining bar), Score, Credits, Equipment status, Combo badge.",
   "All ingredient icons shape+colour coded. Timer colour shift + audio cue. Keyboard hotkeys labelled. Screen reader order announcements.",
   "fusionchef_highscore, fusionchef_recipes_unlocked, fusionchef_credits, fusionchef_settings",
   "Simultaneous orders must not share ingredient queue. Kitchen fire state must block only affected equipment. Wrong-order penalty must not drop score below 0.",
   "Multi-order overlap, fire state isolation, score floor, 10-table stress test, mobile tap accuracy on ingredient belt."),

  (17,"StellarSurf","Sports","Sports","Medium",C_ORANGE,
   "Zero-gravity asteroid surfing sport. Player rides plasma waves on asteroids, performing tricks while racing to the finish buoy.",
   "Balance on wave using tilt/keys. Perform trick inputs mid-air. Collect star tokens. Race 3 rivals. Finish line within par time for bonus.",
   "Desktop: Left/Right balance, Up/Down tricks, Space grab. Touch: tilt device or swipe. Controller: left stick balance, ABXY tricks.",
   "Trick points: flip=200, grab=150, spin=300, combo x1.5 per additional trick. Race position bonus. Star token: 100pts each. Par time bonus: remaining_sec*20.",
   "Tutorial wave, single rival, 3 rivals, storm wave, trick challenge, pro circuit.",
   "Wave Boost, Trick Multiplier, Balance Lock, Star Magnet, Slow Rivals.",
   "Rival surfer (collision), Space debris, Gravity spike, Vortex eddy, Boss rival (cheats).",
   "Surf rock in space style 130BPM. Wave: rushing whoosh. Trick land: crowd cheer. Collision: wipeout splash effect. Victory: brass surf sting.",
   "Neon asteroid wave with gradient sky. Rider: stylised spacesuit sprite. Wave: translucent plasma with foam. Trick animations: smooth keyframes. Rivals: distinct colour suits.",
   "Speed indicator, Trick meter, Balance gauge, Position (P1-P4), Star count, Timer, Boost bar.",
   "Balance mechanic also keyboard-only viable. Tilt can be disabled. Rivals distinct by colour+shape. Screen reader position updates.",
   "stellarsurf_highscore, stellarsurf_circuit_wins, stellarsurf_best_trick, stellarsurf_settings",
   "Trick input window must not overlap balance input. Rival AI must not rubber-band unfairly. Wave speed must scale with difficulty only.",
   "Trick combo detection, rival AI fairness, wave speed scaling, tilt disable, 60FPS trick animations."),

  (18,"ChromaShift","Arcade","Arcade","Medium",C_CYAN,
   "Colour-dimension lab. A spherical probe must match the colour of incoming portals to pass through without shattering.",
   "Portals of various colours fall. Player cycles probe colour to match before impact. Multiple portals simultaneously from level 10. Wrong colour = shatter.",
   "Desktop: Left/Right arrows cycle colour. Keyboard: number keys 1-5 select colour directly. Touch: swipe up/down cycle, tap left/right for direct select.",
   "Correct match: 200pts. Instant match (<0.5s): 300pts. Streak x multiplier (max x6 at 30 streak). Wrong: -100, break streak. Survival time bonus: 10pts/second.",
   "3 colours, slow portals. 4 colours. 5 colours, faster. Mixed sizes. Simultaneous portals. Hidden colour portals.",
   "Chromatic Shield (any colour passes 5s), Slow Portals (0.5x speed 8s), Colour Lock (auto-match 3 portals), Portal Destroyer (obliterate incoming portal), Double Score (15s).",
   "Split Portal (requires two colours), Mirror Portal (wrong colour succeeds), Ghost Portal (must remember shown colour then it hides), Speed Surge (2x portal speed sudden), Bomb Portal (wrong = -500pts).",
   "Pulsing electronic beats. Colour cycle: whoosh. Correct match: harmonic pop. Wrong: glass shatter + buzz. Streak milestone: escalating chime chord. Max streak: euphoric electronic burst.",
   "Minimalist dark background. Probe: large glowing sphere in current colour. Portals: rings with colour glow halos. Colour transitions: smooth gradient morph. Particle burst on correct match.",
   "Probe colour indicator (center bottom label), Score (top-right), Lives (top-left circles), Streak counter (centre-top), Incoming portal warning arrows (side).",
   "Colour cycle also via number keys (not colour-only navigation). Each colour has shape indicator. Audio cue for each colour. Screen reader colour announcements.",
   "chromashift_highscore, chromashift_streak, chromashift_achievements, chromashift_settings",
   "Colour cycle wrap-around must be seamless. Simultaneous portals must not collide detection. Ghost portal must reveal briefly before hiding consistently.",
   "Cycle speed test, simultaneous portal collision detection, ghost reveal timing, colour-shape mode, 60FPS particle."),

  (19,"FrostFortress","Survival","Survival","Hard",C_CYAN,
   "Arctic research station under siege. Player manages resources, defences, and survivor morale during an endless polar night storm.",
   "Balance heat fuel, food, medicine, and defender assignments. Storm waves bring ice creatures. Send defenders to battle posts. Repair stations. Manage 10 survivors.",
   "Desktop: click to assign, drag resources, keyboard hotkeys H/F/M/D. Touch: tap assign, hold drag. Keyboard: full navigate+assign.",
   "Survive each night: 1000pts. Survivor alive bonus: 100 each at dawn. Resource efficiency: (remaining/starting)*500. Kill credits: 50 per creature. Nights survived = score.",
   "Night 1-3: small creatures, moderate storm. N4-7: medium pack. N8-12: armoured. N13-18: boss + pack. N19+: endless escalation.",
   "Supply Drop (random resources), Thermal Shield (stop heat drain 1 night), Medkit Cache (heal all survivors), Creature Repellent (no attack 1 night), Emergency Generator (double heat 30s).",
   "Ice Wolf (fast, weak), Frost Troll (slow, strong), Blizzard Wraith (bypasses walls), Pack Leader (buffs others), Frozen Boss (multi-phase).",
   "Arctic wind howl ambience. Creature approach: growl + footsteps. Combat: muffled blows. Resource collect: satisfying thud. Survivor morale low: quiet sobs. Victory dawn: birds + sun sting.",
   "Top-down snow base. Dark navy night with blizzard particle overlay. Structures: blocky arctic style. Creatures: white/blue icy sprites. Interior warmth glow contrast. Survivor portraits in HUD.",
   "Survivors status panel, Resource bars (heat/food/medicine), Night timer, Wave incoming warning, Defender assignment grid, Kill count.",
   "All resource states have audio+visual cues. Survivor portraits are not solely colour-coded. Keyboard assignment complete. Screen reader resource warnings.",
   "frostfortress_nights, frostfortress_survivors, frostfortress_highscore, frostfortress_settings",
   "Survivor death must trigger immediate morale penalty. Resource drain must not go negative. Creature pathfinding must not pass through sealed stations.",
   "10-survivor management stress test, resource floor, creature pathfinding walls, morale cascade, iOS touch assignment."),

  (20,"MemoryMatrix","Memory","Memory","Easy",C_PURPLE,
   "Neural palace memory training. Flash sequence of glowing symbols on a matrix. Player reproduces sequence with increasing length.",
   "Watch sequence flash, reproduce it in order. Speed increases with level. New symbols added. Distraction symbols appear from level 10.",
   "Desktop: click tiles. Keyboard: numpad or arrow keys. Touch: tap tiles.",
   "Correct sequence: base * length. Speed bonus: (par_time - input_time) * 20. Perfect round: +500. Streak 3: x1.5. Longest streak = leaderboard.",
   "3x3 grid, seq 3. 4x4 grid. Faster flash. Distractor symbols. Moving tiles. 3D rotation of grid.",
   "Replay (re-show sequence once), Slow Flash (0.5x flash speed), Highlight Helper (outline correct tiles during input), Extra Life, Grid Freeze (pause mid-input).",
   "Decoy Flash (wrong symbols mixed), Speed Flash (extremely fast display), Grid Rotation (tiles shuffle), Colour Fade (tiles dim during input), Flip (mirror the grid).",
   "Soft ambient focus music. Tile flash: distinct tone per position. Correct input: affirming chime. Wrong: gentle buzz. Sequence complete: harmonic chord. New record: fanfare.",
   "Dark neural-network background. Tiles: hexagonal, glowing neon. Each symbol: distinct glyph + colour. Flash animations: smooth fade-in/out. Background: pulsing synaptic connections.",
   "Sequence length display, Score, Lives (3), Level, Current input progress dots, Streak badge.",
   "Each tile has distinct glyph for colorblind users. Keyboard tile grid navigable. Flash speed adjustable in accessibility settings. Screen reader tile positions.",
   "memorymatrix_highscore, memorymatrix_longest_seq, memorymatrix_level, memorymatrix_settings",
   "Sequence generation must be seeded per level for reproducibility. Input must lock during flash phase. Distractor symbols must not match sequence symbols.",
   "Sequence seed reproducibility, input-lock during flash, distractor uniqueness, grid rotation sync, 60FPS on 5x5 grid."),
]

# Games 21-100: condensed single-line expanded format
GAMES_100 = [
  (21,"Sokobot","Puzzle","Puzzle","Medium",C_TEAL,
   "Futuristic warehouse. Robot pushes crates onto target pads to unlock escape door.",
   "Push crates to targets. Can't pull. Plan moves. Undo available. Minimum moves for bonus.",
   "Arrow keys / WASD push direction. Touch: swipe direction. Keyboard: Z undo, R restart.",
   "Crate placed: 300pts. All placed: 1000 bonus. Move efficiency: (optimal-used)*50. Undo penalty: -20 each.",
   "1 crate 1 target. 2 crates. T-intersections. Multi-room. Crate chains. 50-level set.",
   "Undo, Hint Path, Teleport Crate, Wall Remove, Auto-Solve one crate.",
   "Ice Floor (crate slides), Heavy Crate (2 pushes), Locked Crate (needs key), Bomb Crate (explodes if pushed too far), Gravity Crate (falls).",
   "Industrial ambient. Crate push: metal scrape. Correct place: satisfying click. Undo: mechanical reverse. Solve: factory horn.",
   "Isometric warehouse, steel floor, orange crate highlights, target pads glow green, parallax ceiling lights.",
   "Moves counter, Undos left, Score, Level, Optimal moves hint (optional), Restart button.",
   "High-contrast crate/target. Keyboard complete. Screen reader move announcements. Reduced motion: instant moves.",
   "sokobot_highscore, sokobot_level, sokobot_min_moves, sokobot_settings","Crate-on-crate push must be blocked. Ice slide must stop at wall. Undo must not go beyond level start.",
   "All 50 levels solvable test, ice slide physics, undo stack limit, isometric rendering, mobile swipe accuracy."),

  (22,"AquaFlow","Physics","Physics","Medium",C_CYAN,
   "Pipe network puzzle. Route water from source to all plants by connecting pipe segments on a grid.",
   "Drag pipe pieces to connect source to all endpoints. Water flows in real-time. Pressure drops over length. Score for efficiency.",
   "Click/drag pipe placement. Rotate: R key or right-click. Touch: tap place, swipe rotate. Keyboard: arrow nav + Enter place.",
   "All endpoints reached: 1000pts. Pressure efficiency: avg_pressure * 500. Fewer pipes used: (max-used)*100. Time bonus.",
   "2 endpoints, 3 pipe pieces. T-junctions. Pressure mechanics. Elevation changes. Timed flow. Moving endpoints.",
   "Extra Pipe, Pressure Boost, Flow Accelerator, Pipe Cleaner (removes blockage), Instant Connect.",
   "Rust Block (must route around), Pressure Valve (limits flow), Broken Pipe (leaks pressure), One-way Valve, Blocked Endpoint (needs key).",
   "Water flow ambient. Pipe connect: click. Water running: gentle flow. Pressure warning: hiss. All connected: satisfying whoosh-fill.",
   "Blueprint grid art, navy background, cyan water with flow animation, pipe pieces grey metal with blue water inside, pressure gradient colour.",
   "Pressure gauges on endpoints, Pipe inventory, Score, Level, Water flow animation, Leak indicators.",
   "Pipe fill colour + pressure indicator pattern. Keyboard grid navigate. Screen reader pressure announcements. High-contrast mode.",
   "aquaflow_highscore, aquaflow_level, aquaflow_efficiency, aquaflow_settings","Pressure must not go negative. Loops in pipe network must drain pressure correctly. Moving endpoints must recalculate flow.",
   "Loop pressure drain, moving endpoint sync, pressure floor, 20x20 grid 60FPS, touch pipe rotation."),

  (23,"SpeedScript","Educational","Educational","Easy",C_YELLOW,
   "Coding academy. Student types code snippets accurately and fast to deploy space satellites.",
   "Code lines appear. Type exactly, including syntax. Character accuracy tracked. Completion deploys satellite. Mistakes cause rocket failure.",
   "Keyboard only. All characters. Backspace to correct. Esc pause.",
   "WPM score. Accuracy %. WPM * accuracy_bonus. Streak for no mistakes. Level time bonus.",
   "Simple variable assignments. Functions. Loops. Classes. Full programs. Speed challenges.",
   "Auto-Complete (one word), Hint Syntax (show one char), Time Extend, Error Shield (one typo forgiven), Double WPM (20s).",
   "Syntax Bomb (must delete + retype line), Scramble (shuffles one word), Cursor Jump, Time Warp (speeds up code scroll), Error Cascade (one mistake adds another).",
   "Electronic coding ambient. Keystroke: mechanical keyboard sounds. Error: buzzer. Deploy success: rocket launch SFX. Perfect accuracy: chime.",
   "Dark IDE aesthetic. Code font monospace, syntax-highlighted. Background: star map with satellite parallax. Error highlight: red underline. Accurate line: green tick.",
   "WPM counter, Accuracy %, Current line, Lines remaining, Score, Error count, Timer.",
   "Large font option. All characters typeable. Screen reader line announcements. Keyboard-only by design. High-contrast syntax highlight.",
   "speedscript_highscore, speedscript_wpm, speedscript_accuracy, speedscript_settings","WPM calculation must handle all keyboard layouts. Auto-complete must not advance past current position. Backspace must only delete last character.",
   "WPM algorithm, layout compatibility, auto-complete boundary, error cascade max, 60FPS code scroll."),

  (24,"DungeonDice","Strategy","Strategy","Medium",C_PURPLE,
   "Dungeon delve via dice combat. Hero fights monsters using strategic dice assignment. Resource management between rooms.",
   "Roll dice pool. Assign dice to attack, defend, heal actions. Beat enemy dice roll. Choose next room. Collect loot.",
   "Click dice drag to slot. Keyboard: Tab select die, arrow move to slot. Touch: tap+drag.",
   "Monster killed: HP-based points. Dungeon floor cleared: 2000pts. Loot value. No-damage bonus: 500. Boss kill: 5000.",
   "3 dice, 3 rooms. 4 dice. Special dice. Boss floor. Curse rooms. Prestige dungeon.",
   "Extra Die, Loaded Die (choose any face), Shield Die, Reroll (any one die), Loot Multiplier.",
   "Armoured Monster (reduces attack dice), Curse (removes one die for 2 rooms), Trap Room (must defend first), Boss Monster (multi-phase), Mimic (disguised loot).",
   "Dungeon stone ambience. Dice roll: clatter. Attack: sword clash. Defend: shield thud. Monster defeat: death groan. Floor clear: triumphant horn.",
   "Dark dungeon stone background. Dice: 3D rendered style. Monster portraits: illustrated fantasy. Loot: glowing gold items. Health bars: red gems. Parallax torch flicker.",
   "HP (hero), Monster HP, Dice pool, Slot panel (attack/defend/heal), Floor/Room number, Loot inventory.",
   "Dice face values always text + symbol. Keyboard complete assignment. Screen reader dice roll results. Colorblind dice patterns.",
   "dungeondice_highscore, dungeondice_floor, dungeondice_loot, dungeondice_settings","Dice assignment must lock before resolution. Curse effect must track duration correctly. Mimic reveal must not show loot value.",
   "Dice assignment lock, curse duration, mimic detection, 60FPS dice animation, mobile drag accuracy."),

  (25,"NightMarket","Idle","Idle","Easy",C_ORANGE,
   "Glowing night bazaar. Player runs a street market stall, selling goods to AI customers, upgrading stall, hiring vendors.",
   "Customers arrive at set rate. Sell goods by clicking or auto-sell. Use profits to upgrade stall, hire staff, unlock new goods. Day/night cycle affects customer flow.",
   "Click to sell. Click to upgrade. Keyboard Tab/Enter navigate shop. Touch: tap sell, tap upgrade.",
   "Revenue per second as primary metric. Total earned as score. Prestige multiplier. Day milestone bonuses.",
   "One stall one good. Three goods. Staff automation. Rival stall events. Festival days. Prestige.",
   "Flash Sale (3x revenue 30s), Supply Delivery (instant stock), Staff Bonus (x2 sell speed 1min), Festival Mode (5x customers 2min), Market Legend (permanent +10% per use).",
   "Rival Stall (steals customers), Supply Delay (no restock 1 cycle), Tax Inspector (lose 20% revenue), Protest (0 customers 2 cycles), Power Outage (lose auto-sell).",
   "Market crowd ambient. Sale ding: cash register. Upgrade: construction tap. Rival event: competitive jingle. Festival: lively drum beat.",
   "Isometric night market stall. Warm lantern light. Colourful goods icons. Customer sprites: diverse characters. Background: parallax city street at night. Text: stylised market signage.",
   "Revenue/sec, Total earned, Customer queue, Stock level, Staff slots, Day counter, Upgrade shop panel.",
   "All income states text-announced. Keyboard shop nav. Screen reader revenue update. Reduced motion: static customers.",
   "nightmarket_earned, nightmarket_rps, nightmarket_prestige, nightmarket_unlocks, nightmarket_settings","Offline earnings must cap at 24hr. Rival stall must not reduce revenue below 0. Festival events must not stack.",
   "Offline cap, rival floor, festival stack, upgrade multiplier accumulation, mobile tap precision on stall."),

  (26,"MindBridge","Logic","Logic","Hard",C_NAVY,
   "Telepathic network puzzle. Connect mind-nodes of matching types with bridges. No bridge may cross another. Fill all cells.",
   "Draw bridges between matching nodes. No crossings. All cells must be used. Minimum bridges for efficiency bonus.",
   "Click+drag to draw bridge. Click bridge to delete. Keyboard: navigate grid, Enter draw. Touch: swipe bridge.",
   "Puzzle solved: 1000pts. No-crossing perfect: 500 bonus. Cell efficiency: (filled/total)*300. Time bonus.",
   "4x4 grid 3 colours. 6x6. 8x8. No-cross strict. Diagonal nodes. Time limit.",
   "Bridge Reveal (show one correct bridge), No-Cross Hint, Extra Node, Undo, Time Pause.",
   "Fixed Node (can't move bridge), Cross Trap (false path looks valid), Blocker Cell (can't bridge through), Colour Decoy (similar shade), Time Drain.",
   "Meditative ambient. Bridge draw: pencil scratch. Correct solve: harmonic tone. Cross attempt: blocked buzz. Completion: zen chord.",
   "White grid on dark slate. Nodes: bright colour circles. Bridges: matching colour lines. Invalid cross: red flash. Clean minimal sans-serif UI.",
   "Grid display, Nodes count, Score, Time (timed levels), Bridge count, Undo button, Level progress.",
   "Colour + number label on each node. High-contrast mode. Keyboard grid nav. Screen reader bridge status. Reduced motion: instant bridge draw.",
   "mindbridge_highscore, mindbridge_level, mindbridge_perfect, mindbridge_settings","Bridge removal must recalculate all cell-fill status. Cross detection must handle diagonal bridges. Level must be validated solvable on generation.",
   "Cross detection algorithm, cell fill accuracy, solvability validation, 8x8 60FPS, touch drag precision."),

  (27,"TerraForm","Strategy","Strategy","Hard",C_GREEN,
   "Barren planet colonisation. Player terraforms a procedurally generated alien world using limited terraforming modules placed on a hex grid.",
   "Place atmosphere, water, soil, and temperature modules. Watch planet stats change. Unlock habitability zones. Manage power budget. Race against meteor strikes.",
   "Click hex to place module. Hotkeys 1-6 module types. Touch: tap hex, bottom bar select. Keyboard: nav hex grid, hotkey place.",
   "Habitability % * 1000 as score. Zone unlocked: 500pts each. Power efficiency: (max_power-used)/max_power * 300. Meteor survived: 200.",
   "Single continent, 4 modules. Multiple continents. Power management. Dynamic weather. Meteor field. Full terraforming.",
   "Solar Boost (double power 30s), Atmosphere Seed (instant atmo boost), Water Drop (floods zone), Shield Dome (block meteors 20s), Nano-Soil (double soil efficiency).",
   "Meteor Strike (destroys module), Power Surge (disables modules 10s), Acid Rain (reduces soil quality), Volcanic Eruption (blocks 3 hexes), Solar Flare (overloads power).",
   "Ambient alien wind. Module place: sci-fi click. Meteor: deep impact boom. Habitability increase: hopeful chord. Planet complete: epic orchestral swell.",
   "3D-ish hex planet surface. Module icons: distinct sci-fi designs. Habitability colour overlay (red to green gradient). Atmosphere layer parallax effect. Power grid lines glow.",
   "Habitability % gauge, Power bar, Module inventory, Planet stats panel (atmo/water/soil/temp), Meteor warning, Turn/day counter.",
   "Module icons with text labels. Screen reader planet stat changes. Keyboard hex nav complete. Colorblind habitability: pattern fill instead of colour.",
   "terraform_highscore, terraform_planet_score, terraform_modules, terraform_settings","Meteor must not destroy identical modules simultaneously to cause cascade. Power budget must clamp at max. Hex edge cases at grid boundary.",
   "Power budget clamp, meteor cascade prevention, hex boundary, 60FPS planet render, habitability calculation precision."),

  (28,"ChromaCraft","Puzzle","Puzzle","Easy",C_PINK,
   "Textile studio. Mix paint colours to match target swatches by combining primary/secondary colours on a canvas palette.",
   "Add drops of primary colours to palette. Mix to achieve target colour within tolerance. Limited drops per round. Timed from level 10.",
   "Click colour droppers. Keyboard: 1=red 2=blue 3=yellow Enter mix. Touch: tap droppers tap mix.",
   "Match within 5% tolerance: 500pts. Exact match: 1000pts. Drop efficiency: (max-used)*100. Streak bonus.",
   "2 primaries mix. 3 primaries. Secondaries + primaries. Tints + shades. Complementary. Timed expert.",
   "Colour Hint (show ratio), Drop Multiplier, Instant Mix, Undo Last Drop, Tolerance Boost (10% wider).",
   "Fading Target (colour shifts over time), Extra Drops Locked, Decoy Swatch (wrong distractor), Rapid Target Swap, Colour Blind Challenge.",
   "Art studio ambient. Drop: drip sound. Mix: swirl. Correct match: chime. Wrong: buzz. Perfect: triumphant flourish.",
   "Bright art studio background. Canvas: textured white. Paint drops: vivid splatter effect. Target swatch: framed sample. Colour wheel reference (optional). Warm studio light parallax.",
   "Target swatch, Current mix colour, Drop count, Score, Streak, Timer (timed levels), Colour history.",
   "Colour values shown as hex+name text. Tolerance indicator as text %. Keyboard dropper controls. Screen reader colour announcements.",
   "chromacraft_highscore, chromacraft_level, chromacraft_perfect, chromacraft_settings","Colour mixing must use additive RGB model consistently. Tolerance must be delta-E calculation not RGB distance. Undo must revert mix state exactly.",
   "Delta-E tolerance accuracy, RGB model consistency, undo revert, timed mode timer, 60FPS mix animation."),

  (29,"VoxelVault","Adventure","Adventure","Medium",C_GOLD,
   "3D voxel dungeon treasure hunt. Navigate procedurally generated voxel caves. Collect treasure, fight cube monsters, escape via portal.",
   "First-person(ish) voxel navigation. Mine blocks to open paths. Fight monsters. Collect treasure. Find portal. Time-limited per level.",
   "WASD move, mouse look (click-locked), E mine/interact, Space jump. Touch: virtual WASD + look swipe. Keyboard: full nav.",
   "Treasure: value-based pts. Monster kill: 300pts. Portal reached: 2000pts. Time remaining * 50. All treasure: x2 multiplier.",
   "Small cave, 5 treasures. Branching cave. Multi-level. Boss cube. Trap puzzles. Endless generation.",
   "Speed Pick (instant mine), Monster Freeze (5s), Treasure Radar (show nearby), Shield Block (one hit), Torch (illuminate dark zone).",
   "Cube Zombie (slow melee), Voxel Spider (fast, small), Rock Golem (high HP), Trap Block (look identical to normal), Portal Mimic (wrong portal).",
   "8-bit cave ambience. Footstep: pixel crunch. Mine: block break. Monster: low growl. Treasure: sparkle. Portal open: magical hum.",
   "Low-poly voxel style. Bright jewel tones for treasure, grey stone for walls, bright monster colours. CSS 3D transforms for voxel rendering. Torch particle effects.",
   "HP (voxel hearts), Treasure collected/total, Timer, Mini-map top-down 2D, Monster radar dots, Pick durability.",
   "Voxel navigation keyboard-complete. Monster types shape-distinct. Screen reader room description. High-contrast torch mode.",
   "voxelvault_highscore, voxelvault_level, voxelvault_treasure, voxelvault_settings","Portal mimic detection must be consistent. Mine animation must not skip frames. Procedural gen must guarantee reachable portal.",
   "Portal mimic logic, mine animation, reachable portal guarantee, 60FPS CSS 3D, mobile look swipe."),

  (30,"RetroRally","Racing","Racing","Easy",C_RED,
   "8-bit top-down car rally. Player drives through pixel-art rally stages, dodging obstacles and rival cars to reach the finish.",
   "Top-down scrolling track. Steer around obstacles. Rivals try to block. Collect fuel pickups. Finish before fuel runs out.",
   "Arrow keys steer. Space drift. Touch: left/right buttons, tap brake. Keyboard: complete.",
   "Finish position bonus. Obstacle dodge: 50pts each. Rival overtake: 100pts. Fuel efficiency: remaining * 20.",
   "Straight road, 1 rival. Winding road, 2 rivals. Obstacles. Night race. Rain race. Championship.",
   "Nitro (3s boost), Fuel Pack, Shield Bumper, EMP (disable rivals 5s), Perfect Corner.",
   "Rival Car (block/ram), Oil Slick, Pothole, Traffic Cone, Police Car (must dodge).",
   "8-bit racing music 130BPM. Engine rev. Collision: crunch. Drift: tyre screech. Finish: checkered flag jingle.",
   "Pixel art top-down. Bright green grass, grey road, pastel rival cars. 8-colour palette. Screen shake on collision. Road lines parallax scroll.",
   "Speed gauge, Fuel bar, Position P1-P5, Rival positions, Lap/Stage counter, Timer.",
   "Rivals colour+shape distinct. Screen reader position updates. Keyboard complete. High-contrast road markings.",
   "retrorally_highscore, retrorally_championship, retrorally_fastest_lap, retrorally_settings","Rival AI must not clip through walls. Fuel must not deplete mid-finish animation. Screen shake must not affect input detection.",
   "Rival wall clipping, fuel floor, screen shake input, 60FPS pixel scroll, championship save state."),

  (31,"InfiniteJumper","Endless Runner","Endless Runner","Easy",C_YELLOW,
   "Neon vertical infinite climber. Jump between rising platforms above an endless abyss. Platforms dissolve after touch.",
   "Tap/click to jump to alternating sides. Platforms rise faster over time. Dissolving platforms require speed. Spring platforms give super-jump.",
   "Left arrow/A = left, Right arrow/D = right. Touch: tap left/right screen half. Space = jump any side.",
   "Platform hit: 10pts. Super-jump height bonus: 50pts. Survival time: 1pt/sec. New height record: x2.",
   "Slow rise, solid platforms. Faster, dissolving. Mixed platform types. Narrow platforms. Speed burst phases. Endless.",
   "Shield (survive one fall), Platform Freeze (stop dissolve 5s), Slow Mode (0.7x rise speed 8s), Double Jump, Magnet (attract to nearest platform).",
   "Dissolving Platform (disappears after 1.5s), Moving Platform, Fake Platform (vanishes on touch), Spike Platform (damages), Speed Burst Zone (sudden speed increase).",
   "Upbeat looping electronic. Jump: spring pop. Land: solid thud. Fall: descending swoosh. New height: ascending chime. Game over: deep thud.",
   "Dark abyss gradient. Platforms: neon coloured by type (solid=blue, dissolving=orange, spring=green). Player: bright sprite with trail. Background: parallax vertical star columns.",
   "Height counter (top-center), Score (top-right), Lives (bottom-left), Platform type legend (bottom-right small icons).",
   "Platform type icon on each tile. Keyboard split input. Screen reader height milestone announcements. Reduced motion: no background parallax.",
   "infinitejumper_highscore, infinitejumper_height, infinitejumper_achievements, infinitejumper_settings","Dissolve timer must be consistent per platform type. Fall detection must not false-trigger on edge land. Platform spawn must guarantee reachable next platform.",
   "Dissolve timer consistency, fall detection edge, reachable spawn, 60FPS vertical scroll, iOS touch split screen."),

  (32,"CipherQuest","Adventure","Adventure","Hard",C_GOLD,
   "Spy thriller. Decode intercepted enemy messages using substitution, Caesar, and Vigenere ciphers to stop a global threat.",
   "Message displayed. Player selects cipher type, inputs key, decodes. Partial decodes give clues. Timer per mission. Wrong attempts limited.",
   "Click cipher selector. Type key. Enter submit. Keyboard: Tab navigate, Enter submit. Touch: virtual keyboard + tap selectors.",
   "Full decode: 2000pts. Partial clue use: -200 each. Speed bonus: (time_limit-elapsed)*30. Wrong attempt: -100 each. Mission clear: 1000 bonus.",
   "Caesar cipher easy. Substitution medium. Vigenere. Combined. Auto-decryption attack. Double-encrypted.",
   "Cipher Hint (-1 character reveal), Key Fragment (partial key), Brute Force (auto-attempt 3 options), Time Extend, Extra Attempt.",
   "Red Herring Message (decoy), Time Trap (wrong decode subtracts time), Cipher Switch (method changes mid-decode), Encrypted Key (key is itself encoded), Self-Destructing Message.",
   "Thriller ambient. Keyboard type: mechanical. Decode click: lock turning. Correct decode: satisfying unlock. Wrong: alarm. Mission complete: spy fanfare.",
   "Dark spy aesthetic. Encrypted text: monospace red. Decoded: green. Background: parallax city surveillance footage desaturated. Cipher interface: old typewriter style.",
   "Message display, Decode input, Cipher selector, Attempts remaining, Score, Timer, Partial decode progress.",
   "Cipher type visually and text-labelled. Keyboard complete. Screen reader decoded progress. High-contrast text mode.",
   "cipherquest_highscore, cipherquest_missions, cipherquest_time, cipherquest_settings","Caesar wrap-around must be correct (Z+1=A). Vigenere key length must match message handling. Wrong attempt counter must not undercount.",
   "Caesar wraparound, Vigenere key handling, attempt counter, partial decode logic, mobile virtual keyboard layout."),

  (33,"BlobWars","Strategy","Strategy","Medium",C_TEAL,
   "Amoeba territory conquest. Expand blob colonies to cover the board by splitting and moving blobs. Turn-based vs AI.",
   "Move blob to adjacent cell: it splits, leaving one behind, growing territory. Jump over gap: moves without split. Capture adjacent enemy blobs. Board full ends game.",
   "Click source blob, click destination. Keyboard: arrow select, Enter move. Touch: tap source, tap destination.",
   "Territory at game end: cells*100. Capture combo: x1.2 per chain capture. Board fill bonus: 2000pts. Win vs AI: 3000pts.",
   "5x5 1 opponent. 8x8. Two opponents. Three opponents. Handicap mode. Endless tournament.",
   "Mega Blob (capture radius +1), Territory Shield (protect 3 cells 2 turns), Absorb (instantly absorb adjacent enemy), Clone Wave (split all blobs simultaneously), Camouflage (enemy can't target for 1 turn).",
   "Aggressive AI (immediate counter), Defensive AI (blocks splits), Kamikaze blob (sacrifices to split board), Shield Blob (immune to capture), Multiplier Blob (captured = 2 normal).",
   "Upbeat strategy jingle. Blob move: wet splat. Capture: pop. AI move: thinking hum then click. Game end: territory tally SFX sequence.",
   "Colourful blob art on grid. Player: blue blobby sprites. AI: red/orange. Territory: colour fills. Animations: jiggly blob movement. Background: abstract organic parallax.",
   "Territory count (player vs AI), Turn indicator, Move preview highlight, Score, AI thinking indicator, Level.",
   "Territory colour + pattern coded. Keyboard select-move complete. Screen reader turn and capture announcements. Reduced motion: instant moves.",
   "blobwars_highscore, blobwars_wins, blobwars_territory, blobwars_settings","AI must not make illegal moves. Blob count must never exceed board size. Capture must be atomic per turn.",
   "AI illegal move prevention, board overflow, atomic capture, 60FPS blob animation, keyboard select accuracy."),

  (34,"NebulaNote","Rhythm","Rhythm","Medium",C_VIOLET,
   "Space observatory music. Tune cosmic radio dishes by matching note frequencies shown as planetary orbits. Procedurally generated space symphonies.",
   "Planet orbits represent notes. Rotate dish to align with current note orbit. Hit on alignment tick. Combo extends dish range.",
   "Left/Right rotate dish. Space confirm align. Touch: swipe rotate, tap confirm. Keyboard: complete.",
   "Alignment perfect: 250pts. Off-alignment: 0-150. Combo x multiplier. Song clear: 2000pts. Full alignment bonus.",
   "3 note orbits, slow. 5 note orbits. Fast orbits. Overlapping orbits. Reverse orbit. Multi-dish.",
   "Orbit Lock (freeze orbit 3s), Frequency Boost (wider alignment window 10s), Dish Upgrade (range +20% permanent per level), Slow Orbit, Auto-Align (one note).",
   "Interference Wave (shifts dish), Rogue Planet (blocks orbit), Frequency Jam (wrong note forced), Nebula Cloud (hides orbits 2s), Solar Wind (rotation speed changes).",
   "Space ambient with evolving synthesiser. Dish rotate: servo whir. Perfect align: clear bell tone. Combo: harmonic chord build. Song end: cosmic orchestra swell.",
   "Deep space dark blue. Planetary orbit rings: bright gradient lines. Dish: metallic sci-fi design rotating smoothly. Notes visualised as glowing planet sprites on orbit rings.",
   "Dish rotation indicator, Combo counter, Score, Song progress bar, Active orbits count, Alignment window indicator.",
   "Orbit positions also shown as numeric degrees. Keyboard rotate complete. Screen reader alignment feedback. Reduced motion: static orbits with manual trigger.",
   "nebulanote_highscore, nebulanote_songs, nebulanote_combo, nebulanote_settings","Alignment window must be consistent across frame rates. Dish rotation must wrap at 360. Interference must not produce unrecoverable states.",
   "Alignment framerate independence, 360 wrap, interference recovery, 60FPS orbit render, mobile swipe sensitivity."),

  (35,"TimeLock","Puzzle","Puzzle","Hard",C_PURPLE,
   "Clockwork castle escape. Player manipulates clock hands and gear systems to unlock ancient timepiece puzzles.",
   "Set clock hands to target time shown in riddle. Adjust gears to change hand speed ratios. Multiple clocks must all show correct time simultaneously.",
   "Click+drag clock hands. Keyboard: Tab select clock, arrow adjust. Touch: drag hands, tap gears.",
   "Correct time set: 500pts per clock. All simultaneous: 2000 bonus. Gear adjustments efficiency: (optimal-used)*100. Time bonus.",
   "Single clock, simple riddle. Two clocks. Gear ratios. Three clocks with gear linkages. Hidden time (decipher riddle). Moving hands.",
   "Time Freeze (stop all hands 5s), Gear Hint (show optimal gear setting), Hand Lock (lock correct hand), Riddle Solver (decode riddle for you), Extra Gear.",
   "Fast Hand (spins 2x between adjustments), Gear Slip (ratio changes randomly), Riddle Scramble (re-encrypts riddle), Reversed Clock (hands go backwards), Fog of Time (hides one clock).",
   "Clock ambience with ticking. Hand drag: mechanical ratchet. Gear change: cog click. Correct time: chime. All correct: carillon bells fanfare.",
   "Ornate gothic clockwork art. Dark stone + brass gears. Clock faces: parchment with Roman numerals. Gear animations: smooth rotation. Background: parallax castle gears.",
   "Clock faces (all visible), Target time riddle, Gear panel, Adjustments counter, Score, Timer, Current times display.",
   "Clock hands navigable by keyboard (degree input). Screen reader time announcements. High-contrast clock numbers. Gear state text-labelled.",
   "timelock_highscore, timelock_level, timelock_adjustments, timelock_settings","Gear ratio calculation must use integer fractions. Clock hand positions must be pixel-precise at validation. Riddle must always have valid solution.",
   "Gear ratio precision, hand pixel validation, riddle solvability, 60FPS gear animation, touch drag on clock face."),

  (36,"PixelPainter","Educational","Educational","Easy",C_YELLOW,
   "Digital art school. Learn pixel art techniques by completing guided paintings step-by-step, then free-paint canvases.",
   "Follow pixel-by-pixel instructions for guided mode. Choose colours from palette. Fill regions. Shade and highlight. Unlock free-paint with larger canvases.",
   "Click pixel to paint. Click and drag fill. Keyboard: arrow nav, Enter paint, number keys colour. Touch: tap pixel, tap colour.",
   "Guided accuracy: matching pixels * 10pts. Colour match: bonus. Creative mode: engagement time * 1pt/sec. Shared art: virtual likes.",
   "8x8 guided, 4 colours. 16x16, 8 colours. 32x32 free. Animated pixel art. Portrait mode. Advanced shading.",
   "Palette Expand (unlock more colours), Undo Stack (10 undos), Grid Helper (show grid), Colour Picker (sample any pixel), Eraser Buff (wider eraser).",
   "Colour Limit (restricted palette), Canvas Shrink (fewer pixels available), Fading Canvas (pixels fade if not repainted), Guided Strict Mode (must be exact), Time Painting (live timer).",
   "Soft art studio ambient. Pixel paint: soft pop. Fill: whoosh. Undo: eraser squeak. Artwork complete: gallery applause. Unlock: chime.",
   "White canvas with grid, pixel art style. Palette bar at bottom in vivid colours. Zoom control. Guided progress overlay. Background: art studio parallax.",
   "Canvas (center), Colour palette (bottom), Tools (left sidebar), Progress (top-right %), Score, Undo button.",
   "Colour + pattern fill for accessibility. Keyboard pixel navigation. Screen reader colour selected. High-contrast grid lines. Font size adjustable.",
   "pixelpainter_art_data, pixelpainter_level, pixelpainter_score, pixelpainter_settings","Canvas data must save as compressed format. Undo must not undercount. Guided mode pixel order must be deterministic.",
   "Canvas save size, undo count, guided order, 60FPS 32x32 canvas, mobile pixel tap accuracy."),

  (37,"TyphoonTactics","Strategy","Strategy","Hard",C_TEAL,
   "Naval command strategy. Command a fleet in real-time to capture key islands against an adaptive enemy admiral.",
   "Place ships on pre-battle grid. Real-time movement+attack. Resource income from islands. Build new ships. Enemy adapts to player strategy.",
   "Click ship to select, click target to move/attack. Keyboard: QWER ship types, space pause. Touch: tap ship, tap target.",
   "Island captured: 500pts. Ship sunk: based on enemy ship value. Mission clear: 3000pts. Resource efficiency bonus.",
   "2 ships, 1 island. 4 ships, 3 islands. Enemy adapts. Storm weather. Multi-fleet. Campaign.",
   "Depth Charge (area attack), Fog of War Lift (reveal all 10s), Supply Drop (repair +50% HP), Mine Field (deploy mines), Admiral Command (all ships +30% speed 10s).",
   "Enemy Destroyer (fast, weak), Enemy Battleship (slow, powerful), Submarine (invisible unless hit), Mine (stationary, instant-kill), Enemy Admiral Ship (commands fleet).",
   "Naval orchestral + wave ambient. Cannon fire: deep boom. Ship hit: creak+splash. Island capture: flag raise SFX. Enemy move: distant horn. Victory: full naval fanfare.",
   "Top-down ocean grid. Ships: detailed top-down sprites. Ocean: animated wave tiles. Islands: lush miniature art. HUD: naval chart paper style. Weather overlay parallax.",
   "Fleet list (HP/status), Island control map, Resources, Turn/time counter, Fog of war overlay, Command queue panel.",
   "Ship types shape+size distinct. Keyboard select-target complete. Screen reader combat log. Colorblind wave pattern for visibility.",
   "typhoon_highscore, typhoon_islands, typhoon_fleet_wins, typhoon_settings","Enemy AI must not cheat beyond defined stats. Fog of war must be server-side consistent. Island capture must process atomic.",
   "AI stat cap, fog consistency, island capture atomic, 60FPS ocean animation, mobile tap on ship."),

  (38,"GlyphGuardian","Action","Arcade","Medium",C_CYAN,
   "Magic guardian. Draw protective glyphs on-screen with finger/mouse to summon shields and counter enemy spells.",
   "Enemy spells fly toward guardian. Player draws matching glyph pattern to cast counter. Speed and accuracy matter. Fail = HP loss.",
   "Mouse draw. Keyboard: arrow key directional glyph shortcuts. Touch: finger draw glyph on screen.",
   "Correct glyph fast: 300pts. Slow: 150pts. Partial: 50pts. Wrong: 0 + HP loss. Streak x multiplier.",
   "3 glyphs, slow spells. 5 glyphs. Faster. Fake glyphs. Multi-spell. Boss glyph sequence.",
   "Auto-Glyph (one spell auto-blocked), Slow Spell (0.5x speed 8s), Glyph Memory (pattern visible during draw), Extra HP, Double Score.",
   "Fake Glyph Spell (punishes wrong glyph), Fast Barrage (rapid spells), Erase Interference (smears existing draw), Combo Breaker, Boss Spell (complex glyph required).",
   "Mystical orchestral. Draw: quill scratch. Correct glyph: magical burst. Wrong: dark crack. Spell impact: energy explosion. Boss: dramatic orchestra hit.",
   "Dark fantasy background. Glyphs: glowing white on dark background. Spell projectiles: coloured orbs. Guardian: stylised mage sprite. Particle effects on glyph complete.",
   "HP bar, Score, Streak, Spell incoming warning (name label), Glyph palette reference (small corner), Level.",
   "Glyph shapes distinct and recognisable. Keyboard shortcuts for each glyph. Screen reader spell announcements. High-contrast draw canvas.",
   "glyphguardian_highscore, glyphguardian_level, glyphguardian_streak, glyphguardian_settings","Glyph recognition must use template matching not ML. Draw input must not register partial glyphs as complete. Multiple touches must not merge draws.",
   "Template match accuracy, partial glyph rejection, multi-touch isolation, 60FPS draw canvas, mobile finger draw latency."),

  (39,"EchoChamber","Experimental","Experimental","Hard",C_VIOLET,
   "Sound wave puzzle. Player shapes sound waves by placing reflectors in a chamber to direct audio beams to receivers without destructive interference.",
   "Place angled reflectors in grid chamber. Sound beam emits from source. Reaches receiver at correct phase. Phase meter must be green. Interference shown as standing wave.",
   "Click to place reflector. R to rotate. Click existing to remove. Keyboard: grid nav, Enter place. Touch: tap place, two-finger rotate.",
   "Receiver reached correct phase: 1000pts. No interference: 500 bonus. Reflector efficiency: (max-used)*150. Time bonus.",
   "Single beam, 1 receiver. Two beams. Phase matching. Multi-path interference. Frequency splitting. Moving receivers.",
   "Phase Lock (force correct phase 3s), Extra Reflector, Interference Damper (nullify one interference zone), Beam Slow (0.5x propagation 10s), Frequency Reveal (show frequency overlay).",
   "Phase Disruptor (shifts beam phase), Hard Wall (absorbs beam), Resonance Node (amplifies interference), Frequency Gate (only certain frequency passes), Moving Reflector.",
   "Sinusoidal ambient tone. Reflector place: click. Beam reflect: tone pitch change. Destructive interference: dissonant hum. Perfect phase: pure harmonious tone. Level clear: wave resolution chord.",
   "Dark soundproofed room aesthetic. Beams: animated wave lines with colour=frequency. Reflectors: metallic angled surfaces. Phase meter: circular gauge. Interference zones: red standing wave pattern.",
   "Phase meters (all receivers), Reflector inventory, Score, Level, Interference map overlay, Beam frequency legend.",
   "Phase state text-labelled. Keyboard complete nav+place. Screen reader phase announcements. Reduced motion: static beam lines.",
   "echochamber_highscore, echochamber_level, echochamber_perfect, echochamber_settings","Wave interference calculation must be physics-accurate (superposition principle). Reflector angle must snap to defined values. Moving receiver must track beam continuously.",
   "Superposition accuracy, angle snap, moving receiver tracking, 60FPS wave animation, touch rotation gesture."),

  (40,"ZenGarden","Idle","Idle","Easy",C_TEAL,
   "Japanese zen garden. Rake sand patterns, place stones and plants. Meditative idle game where garden grows in beauty over time.",
   "Rake sand to create patterns passively. Place stones and plants for bonus beauty points. Seasons change appearance. Visitors arrive based on beauty score.",
   "Click to place/rake. Keyboard Tab/Enter navigate. Touch: tap place, swipe rake.",
   "Beauty score = main metric. Visitor bonus: 100pts each. Seasonal bonus: x1.5 in-season elements. Perfect garden (all elements): 5000pts.",
   "Empty garden, basic rake. Stones unlock. Plants unlock. Water feature. Lanterns. Seasonal themes.",
   "Rain Blessing (instant beauty boost), Cherry Blossom (spring bonus 2x), Koi Pond Upgrade, Stone Master (unlock rare stones), Bamboo Growth (auto-plant).",
   "Wind Storm (disrupts sand pattern), Animal Intruder (removes one element), Drought (plants wilt), Overgrowth (weeds appear), Tourist Flood (too many visitors, beauty -20%).",
   "Ambient nature: brook, birds, wind. Rake: sand whisper. Stone place: gentle thud. Visitor: soft bell. Season change: delicate chime. Perfect garden: zen harmony chord.",
   "Hand-painted watercolour style. Soft beige sand with grey raked lines. Green plants, grey stones. Seasonal overlays (cherry blossoms pink, snow white). Soft parallax sky.",
   "Beauty score, Visitors today, Seasonal indicator, Elements placed, Sand pattern %, Garden age (days).",
   "All placements keyboard-navigable. Beauty score as text + icon. Screen reader season announcements. Reduced motion: no sway animations.",
   "zengarden_beauty, zengarden_age, zengarden_elements, zengarden_settings","Sand pattern must redraw only changed tiles. Seasonal overlay must layer correctly. Visitor count must not go negative on storm.",
   "Sand redraw optimisation, seasonal layer, visitor floor, 60FPS full garden, mobile place accuracy."),

  # Games 41-100 -- all fully detailed in condensed format
  (41,"LaserLogic","Logic","Logic","Medium",C_YELLOW,"Circuit board laser routing puzzle. Route lasers through logic gates to produce required output signals.",
   "Place and rotate logic gates (AND/OR/NOT/XOR). Input signals fixed. Route to match output requirements. Gates limited per level.",
   "Click to place gate. R rotate. Click existing to remove. Keyboard nav. Touch: tap place, swipe rotate.",
   "Output match: 1000pts. Gate efficiency: (max-used)*200. Speed bonus. Perfect (first attempt): 1500 bonus.",
   "2 inputs AND gate. XOR gates. NOT chains. Complex combinational. Feedback loops. Timed expert.",
   "Extra Gate, Gate Hint, Signal Tracer (show signal path), Unlimited Mode (no gate limit 1 use), Gate Upgrade (improve one gate permanently).",
   "Noise Gate (randomly flips signal), Locked Gate (can't remove), Signal Blocker, Speed Gate (signal races another), Sabotage (changes one gate type).",
   "Electronic circuit hum. Gate place: circuit click. Signal flow: pulsing buzz. Correct output: system chime. Wrong: buzzer. Level clear: digital fanfare.",
   "Dark PCB green background. Gates: clean vector white symbols. Signal paths: animated pulsing lines red/green. Output matches: bright green indicator.",
   "Gate inventory, Output targets, Signal map, Score, Level, Attempts this puzzle.",
   "Gate type text-labelled. Signal state announced screen reader. Keyboard complete. High-contrast signal colours.",
   "laserlogic_highscore, laserlogic_level, laserlogic_perfect, laserlogic_settings","Feedback loop in circuit must not cause infinite simulation. Gate placement must snap to grid. Signal propagation must be deterministic.",
   "Feedback loop detection, grid snap, signal determinism, 60FPS PCB render, touch gate rotation."),
