# Generated by Django 5.0.7 on 2025-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssessmentLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Assessment Leads",
                "ordering": ["-downloaded_at"],
            },
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "location_tags",
                    models.CharField(
                        help_text="e.g., Remote (US), On-site", max_length=100
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        help_text="e.g., Full-Time, Contract", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Full job description, supports basic HTML."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("posted_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Job Positions",
                "ordering": ["-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="StrategyCallLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("revenue_range", models.CharField(blank=True, max_length=100)),
                ("biggest_challenge", models.TextField()),
                ("success_goal", models.TextField()),
                ("ideal_timeline", models.CharField(blank=True, max_length=100)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Strategy Call Leads",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
